// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: hub.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const hubActorLock = `-- name: HubActorLock :exec
SELECT pg_advisory_xact_lock(hashtextextended('hub/' || $1::bigint::text || '/' || $2::bigint::text,0))
`

type HubActorLockParams struct {
	SocietyID int64 `db:"society_id" json:"society_id"`
	UserID    int64 `db:"user_id" json:"user_id"`
}

func (q *Queries) HubActorLock(ctx context.Context, arg HubActorLockParams) error {
	_, err := q.db.Exec(ctx, hubActorLock, arg.SocietyID, arg.UserID)
	return err
}

const hubAddReaction = `-- name: HubAddReaction :one
INSERT INTO channel_reactions(user_id,post_id,comment_id,reaction_type) VALUES($1,$2,$3,$4) ON CONFLICT DO NOTHING RETURNING id
`

type HubAddReactionParams struct {
	UserID       int64  `db:"user_id" json:"user_id"`
	PostID       *int64 `db:"post_id" json:"post_id"`
	CommentID    *int64 `db:"comment_id" json:"comment_id"`
	ReactionType string `db:"reaction_type" json:"reaction_type"`
}

func (q *Queries) HubAddReaction(ctx context.Context, arg HubAddReactionParams) (int64, error) {
	row := q.db.QueryRow(ctx, hubAddReaction,
		arg.UserID,
		arg.PostID,
		arg.CommentID,
		arg.ReactionType,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const hubAttach = `-- name: HubAttach :exec
INSERT INTO channel_attachments(upload_id,post_id,comment_id) VALUES($1,$2,$3)
`

type HubAttachParams struct {
	UploadID  int64  `db:"upload_id" json:"upload_id"`
	PostID    *int64 `db:"post_id" json:"post_id"`
	CommentID *int64 `db:"comment_id" json:"comment_id"`
}

func (q *Queries) HubAttach(ctx context.Context, arg HubAttachParams) error {
	_, err := q.db.Exec(ctx, hubAttach, arg.UploadID, arg.PostID, arg.CommentID)
	return err
}

const hubAttachmentTarget = `-- name: HubAttachmentTarget :one
SELECT a.post_id,a.comment_id,COALESCE(p.society_id,cp.society_id)::bigint AS society_id,
COALESCE(p.status,cp.status)::text AS post_status,c.status AS comment_status
FROM channel_attachments a LEFT JOIN channel_posts p ON p.id=a.post_id LEFT JOIN channel_comments c ON c.id=a.comment_id LEFT JOIN channel_posts cp ON cp.id=c.post_id
WHERE a.upload_id=$1
`

type HubAttachmentTargetRow struct {
	PostID        *int64  `db:"post_id" json:"post_id"`
	CommentID     *int64  `db:"comment_id" json:"comment_id"`
	SocietyID     int64   `db:"society_id" json:"society_id"`
	PostStatus    string  `db:"post_status" json:"post_status"`
	CommentStatus *string `db:"comment_status" json:"comment_status"`
}

func (q *Queries) HubAttachmentTarget(ctx context.Context, uploadID int64) (HubAttachmentTargetRow, error) {
	row := q.db.QueryRow(ctx, hubAttachmentTarget, uploadID)
	var i HubAttachmentTargetRow
	err := row.Scan(
		&i.PostID,
		&i.CommentID,
		&i.SocietyID,
		&i.PostStatus,
		&i.CommentStatus,
	)
	return i, err
}

const hubAttachments = `-- name: HubAttachments :many
SELECT upload_id FROM channel_attachments WHERE post_id IS NOT DISTINCT FROM $1::bigint AND comment_id IS NOT DISTINCT FROM $2::bigint ORDER BY upload_id
`

type HubAttachmentsParams struct {
	PostID    *int64 `db:"post_id" json:"post_id"`
	CommentID *int64 `db:"comment_id" json:"comment_id"`
}

func (q *Queries) HubAttachments(ctx context.Context, arg HubAttachmentsParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, hubAttachments, arg.PostID, arg.CommentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var upload_id int64
		if err := rows.Scan(&upload_id); err != nil {
			return nil, err
		}
		items = append(items, upload_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hubCategories = `-- name: HubCategories :many
SELECT id, code, name, display_order, is_active, created_at, updated_at FROM community_categories WHERE is_active ORDER BY display_order,id
`

func (q *Queries) HubCategories(ctx context.Context) ([]CommunityCategory, error) {
	rows, err := q.db.Query(ctx, hubCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CommunityCategory{}
	for rows.Next() {
		var i CommunityCategory
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.DisplayOrder,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hubCategory = `-- name: HubCategory :one
SELECT id FROM community_categories WHERE is_active AND (id=$1::smallint OR ($1::smallint IS NULL AND code='general'))
`

func (q *Queries) HubCategory(ctx context.Context, id *int16) (int16, error) {
	row := q.db.QueryRow(ctx, hubCategory, id)
	var id_2 int16
	err := row.Scan(&id_2)
	return id_2, err
}

const hubChannel = `-- name: HubChannel :one
SELECT id, society_id, type, name, description, created_at, updated_at FROM society_channels WHERE society_id=$1 AND id=$2
`

type HubChannelParams struct {
	SocietyID int64 `db:"society_id" json:"society_id"`
	ID        int64 `db:"id" json:"id"`
}

func (q *Queries) HubChannel(ctx context.Context, arg HubChannelParams) (SocietyChannel, error) {
	row := q.db.QueryRow(ctx, hubChannel, arg.SocietyID, arg.ID)
	var i SocietyChannel
	err := row.Scan(
		&i.ID,
		&i.SocietyID,
		&i.Type,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hubChannels = `-- name: HubChannels :many
SELECT c.id, c.society_id, c.type, c.name, c.description, c.created_at, c.updated_at, (SELECT count(*) FROM channel_posts p WHERE p.channel_id=c.id AND p.status='active'
 AND (r.last_read_post_id IS NULL OR (p.created_at,p.id)>(r.last_read_created_at,r.last_read_post_id)))::bigint AS unread_count,
 COALESCE((SELECT p.id FROM channel_posts p WHERE p.channel_id=c.id AND p.status='active' AND p.is_important ORDER BY p.created_at DESC,p.id DESC LIMIT 1),0)::bigint AS important_post_id
FROM society_channels c LEFT JOIN channel_read_states r ON r.channel_id=c.id AND r.user_id=$1
WHERE c.society_id=$2 ORDER BY c.type
`

type HubChannelsParams struct {
	UserID    int64 `db:"user_id" json:"user_id"`
	SocietyID int64 `db:"society_id" json:"society_id"`
}

type HubChannelsRow struct {
	ID              int64              `db:"id" json:"id"`
	SocietyID       int64              `db:"society_id" json:"society_id"`
	Type            string             `db:"type" json:"type"`
	Name            string             `db:"name" json:"name"`
	Description     *string            `db:"description" json:"description"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	UnreadCount     int64              `db:"unread_count" json:"unread_count"`
	ImportantPostID int64              `db:"important_post_id" json:"important_post_id"`
}

func (q *Queries) HubChannels(ctx context.Context, arg HubChannelsParams) ([]HubChannelsRow, error) {
	rows, err := q.db.Query(ctx, hubChannels, arg.UserID, arg.SocietyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HubChannelsRow{}
	for rows.Next() {
		var i HubChannelsRow
		if err := rows.Scan(
			&i.ID,
			&i.SocietyID,
			&i.Type,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UnreadCount,
			&i.ImportantPostID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hubClaimCleanup = `-- name: HubClaimCleanup :one
UPDATE channel_uploads SET status='cleanup',lease_until=clock_timestamp()+interval '2 minutes',lease_token=$1
WHERE id=(SELECT id FROM channel_uploads WHERE status IN ('pending','cleanup') AND expires_at<=clock_timestamp()
 AND (lease_until IS NULL OR lease_until<=clock_timestamp()) ORDER BY id FOR UPDATE SKIP LOCKED LIMIT 1) RETURNING id, society_id, uploader_id, file_id, file_path, original_filename, mime_type, file_size, width, height, status, expires_at, lease_until, lease_token, created_at
`

func (q *Queries) HubClaimCleanup(ctx context.Context, leaseToken pgtype.UUID) (ChannelUpload, error) {
	row := q.db.QueryRow(ctx, hubClaimCleanup, leaseToken)
	var i ChannelUpload
	err := row.Scan(
		&i.ID,
		&i.SocietyID,
		&i.UploaderID,
		&i.FileID,
		&i.FilePath,
		&i.OriginalFilename,
		&i.MimeType,
		&i.FileSize,
		&i.Width,
		&i.Height,
		&i.Status,
		&i.ExpiresAt,
		&i.LeaseUntil,
		&i.LeaseToken,
		&i.CreatedAt,
	)
	return i, err
}

const hubClaimUpload = `-- name: HubClaimUpload :execrows
UPDATE channel_uploads SET status='claimed' WHERE id=$1 AND society_id=$2 AND uploader_id=$3 AND status='pending' AND expires_at>clock_timestamp()
`

type HubClaimUploadParams struct {
	ID         int64 `db:"id" json:"id"`
	SocietyID  int64 `db:"society_id" json:"society_id"`
	UploaderID int64 `db:"uploader_id" json:"uploader_id"`
}

func (q *Queries) HubClaimUpload(ctx context.Context, arg HubClaimUploadParams) (int64, error) {
	result, err := q.db.Exec(ctx, hubClaimUpload, arg.ID, arg.SocietyID, arg.UploaderID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const hubComment = `-- name: HubComment :one
SELECT c.id, c.post_id, c.author_id, c.parent_id, c.body, c.status, c.edited_at, c.removal_reason, c.deleted_at, c.deleted_by, c.created_at, c.updated_at FROM channel_comments c JOIN channel_posts p ON p.id=c.post_id WHERE p.society_id=$1 AND c.id=$2
`

type HubCommentParams struct {
	SocietyID int64 `db:"society_id" json:"society_id"`
	ID        int64 `db:"id" json:"id"`
}

func (q *Queries) HubComment(ctx context.Context, arg HubCommentParams) (ChannelComment, error) {
	row := q.db.QueryRow(ctx, hubComment, arg.SocietyID, arg.ID)
	var i ChannelComment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.AuthorID,
		&i.ParentID,
		&i.Body,
		&i.Status,
		&i.EditedAt,
		&i.RemovalReason,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hubCommentIDs = `-- name: HubCommentIDs :many
SELECT c.id FROM channel_comments c JOIN channel_posts p ON p.id=c.post_id
WHERE p.society_id=$1 AND p.id=$2
AND (c.status='active' OR EXISTS(SELECT 1 FROM channel_comments child WHERE child.parent_id=c.id AND child.status='active'))
AND ($3::timestamptz IS NULL OR (c.created_at,c.id)>($3,$4::bigint))
ORDER BY c.created_at,c.id LIMIT $5
`

type HubCommentIDsParams struct {
	SocietyID int64              `db:"society_id" json:"society_id"`
	PostID    int64              `db:"post_id" json:"post_id"`
	AfterAt   pgtype.Timestamptz `db:"after_at" json:"after_at"`
	AfterID   int64              `db:"after_id" json:"after_id"`
	PageLimit int32              `db:"page_limit" json:"page_limit"`
}

func (q *Queries) HubCommentIDs(ctx context.Context, arg HubCommentIDsParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, hubCommentIDs,
		arg.SocietyID,
		arg.PostID,
		arg.AfterAt,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hubCommentRate = `-- name: HubCommentRate :one
SELECT count(*)::bigint AS count,min(c.created_at)::timestamptz AS oldest FROM channel_comments c JOIN channel_posts p ON p.id=c.post_id
WHERE p.society_id=$1 AND c.author_id=$2 AND c.created_at>clock_timestamp()-$3::int*interval '1 second'
`

type HubCommentRateParams struct {
	SocietyID     int64 `db:"society_id" json:"society_id"`
	AuthorID      int64 `db:"author_id" json:"author_id"`
	WindowSeconds int32 `db:"window_seconds" json:"window_seconds"`
}

type HubCommentRateRow struct {
	Count  int64              `db:"count" json:"count"`
	Oldest pgtype.Timestamptz `db:"oldest" json:"oldest"`
}

func (q *Queries) HubCommentRate(ctx context.Context, arg HubCommentRateParams) (HubCommentRateRow, error) {
	row := q.db.QueryRow(ctx, hubCommentRate, arg.SocietyID, arg.AuthorID, arg.WindowSeconds)
	var i HubCommentRateRow
	err := row.Scan(&i.Count, &i.Oldest)
	return i, err
}

const hubCommentView = `-- name: HubCommentView :one
SELECT jsonb_build_object('id',c.id,'post_id',c.post_id,'parent_id',c.parent_id,'status',c.status,
 'author',CASE WHEN c.status='active' THEN jsonb_build_object('id',u.id,'name',u.full_name) ELSE NULL END,
 'body',CASE WHEN c.status='active' THEN c.body ELSE '' END,'created_at',c.created_at,'updated_at',c.updated_at,'edited_at',c.edited_at,
 'reply_count',(SELECT count(*) FROM channel_comments child WHERE child.parent_id=c.id AND child.status='active'),
 'reactions',CASE WHEN c.status='active' THEN COALESCE((SELECT jsonb_object_agg(x.reaction_type,x.n) FROM (SELECT reaction_type,count(*) n FROM channel_reactions WHERE comment_id=c.id GROUP BY reaction_type) x),'{}') ELSE '{}'::jsonb END,
 'my_reactions',CASE WHEN c.status='active' THEN COALESCE((SELECT jsonb_agg(reaction_type ORDER BY reaction_type) FROM channel_reactions cr WHERE cr.comment_id=c.id AND cr.user_id=$1),'[]') ELSE '[]'::jsonb END,
 'attachment_ids',CASE WHEN c.status='active' THEN COALESCE((SELECT jsonb_agg(upload_id ORDER BY id) FROM channel_attachments WHERE comment_id=c.id),'[]') ELSE '[]'::jsonb END) AS data
FROM channel_comments c JOIN channel_posts p ON p.id=c.post_id JOIN users u ON u.id=c.author_id
WHERE p.society_id=$2 AND c.id=$3 AND p.status='active'
`

type HubCommentViewParams struct {
	UserID    int64 `db:"user_id" json:"user_id"`
	SocietyID int64 `db:"society_id" json:"society_id"`
	ID        int64 `db:"id" json:"id"`
}

func (q *Queries) HubCommentView(ctx context.Context, arg HubCommentViewParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, hubCommentView, arg.UserID, arg.SocietyID, arg.ID)
	var data []byte
	err := row.Scan(&data)
	return data, err
}

const hubControlPost = `-- name: HubControlPost :exec
UPDATE channel_posts SET is_pinned=$3,comments_enabled=$4,updated_at=clock_timestamp() WHERE society_id=$1 AND id=$2
`

type HubControlPostParams struct {
	SocietyID       int64 `db:"society_id" json:"society_id"`
	ID              int64 `db:"id" json:"id"`
	IsPinned        bool  `db:"is_pinned" json:"is_pinned"`
	CommentsEnabled bool  `db:"comments_enabled" json:"comments_enabled"`
}

func (q *Queries) HubControlPost(ctx context.Context, arg HubControlPostParams) error {
	_, err := q.db.Exec(ctx, hubControlPost,
		arg.SocietyID,
		arg.ID,
		arg.IsPinned,
		arg.CommentsEnabled,
	)
	return err
}

const hubCreateComment = `-- name: HubCreateComment :one
INSERT INTO channel_comments(post_id,author_id,parent_id,body) VALUES($1,$2,$3,$4) RETURNING id
`

type HubCreateCommentParams struct {
	PostID   int64  `db:"post_id" json:"post_id"`
	AuthorID int64  `db:"author_id" json:"author_id"`
	ParentID *int64 `db:"parent_id" json:"parent_id"`
	Body     string `db:"body" json:"body"`
}

func (q *Queries) HubCreateComment(ctx context.Context, arg HubCreateCommentParams) (int64, error) {
	row := q.db.QueryRow(ctx, hubCreateComment,
		arg.PostID,
		arg.AuthorID,
		arg.ParentID,
		arg.Body,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const hubCreatePost = `-- name: HubCreatePost :one
INSERT INTO channel_posts(society_id,channel_id,author_id,title,body,category_id,comments_enabled,is_pinned,is_important)
VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING id
`

type HubCreatePostParams struct {
	SocietyID       int64   `db:"society_id" json:"society_id"`
	ChannelID       int64   `db:"channel_id" json:"channel_id"`
	AuthorID        int64   `db:"author_id" json:"author_id"`
	Title           *string `db:"title" json:"title"`
	Body            string  `db:"body" json:"body"`
	CategoryID      *int16  `db:"category_id" json:"category_id"`
	CommentsEnabled bool    `db:"comments_enabled" json:"comments_enabled"`
	IsPinned        bool    `db:"is_pinned" json:"is_pinned"`
	IsImportant     bool    `db:"is_important" json:"is_important"`
}

func (q *Queries) HubCreatePost(ctx context.Context, arg HubCreatePostParams) (int64, error) {
	row := q.db.QueryRow(ctx, hubCreatePost,
		arg.SocietyID,
		arg.ChannelID,
		arg.AuthorID,
		arg.Title,
		arg.Body,
		arg.CategoryID,
		arg.CommentsEnabled,
		arg.IsPinned,
		arg.IsImportant,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const hubCreateUpload = `-- name: HubCreateUpload :one
INSERT INTO channel_uploads(society_id,uploader_id,file_id,file_path,original_filename,mime_type,file_size,width,height)
VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING id, society_id, uploader_id, file_id, file_path, original_filename, mime_type, file_size, width, height, status, expires_at, lease_until, lease_token, created_at
`

type HubCreateUploadParams struct {
	SocietyID        int64  `db:"society_id" json:"society_id"`
	UploaderID       int64  `db:"uploader_id" json:"uploader_id"`
	FileID           string `db:"file_id" json:"file_id"`
	FilePath         string `db:"file_path" json:"file_path"`
	OriginalFilename string `db:"original_filename" json:"original_filename"`
	MimeType         string `db:"mime_type" json:"mime_type"`
	FileSize         int64  `db:"file_size" json:"file_size"`
	Width            *int32 `db:"width" json:"width"`
	Height           *int32 `db:"height" json:"height"`
}

func (q *Queries) HubCreateUpload(ctx context.Context, arg HubCreateUploadParams) (ChannelUpload, error) {
	row := q.db.QueryRow(ctx, hubCreateUpload,
		arg.SocietyID,
		arg.UploaderID,
		arg.FileID,
		arg.FilePath,
		arg.OriginalFilename,
		arg.MimeType,
		arg.FileSize,
		arg.Width,
		arg.Height,
	)
	var i ChannelUpload
	err := row.Scan(
		&i.ID,
		&i.SocietyID,
		&i.UploaderID,
		&i.FileID,
		&i.FilePath,
		&i.OriginalFilename,
		&i.MimeType,
		&i.FileSize,
		&i.Width,
		&i.Height,
		&i.Status,
		&i.ExpiresAt,
		&i.LeaseUntil,
		&i.LeaseToken,
		&i.CreatedAt,
	)
	return i, err
}

const hubDeleteComment = `-- name: HubDeleteComment :exec
UPDATE channel_comments SET status=$3,deleted_by=$4,deleted_at=clock_timestamp(),removal_reason=$5,updated_at=clock_timestamp() WHERE id=$1 AND post_id=$2
`

type HubDeleteCommentParams struct {
	ID            int64   `db:"id" json:"id"`
	PostID        int64   `db:"post_id" json:"post_id"`
	Status        string  `db:"status" json:"status"`
	DeletedBy     *int64  `db:"deleted_by" json:"deleted_by"`
	RemovalReason *string `db:"removal_reason" json:"removal_reason"`
}

func (q *Queries) HubDeleteComment(ctx context.Context, arg HubDeleteCommentParams) error {
	_, err := q.db.Exec(ctx, hubDeleteComment,
		arg.ID,
		arg.PostID,
		arg.Status,
		arg.DeletedBy,
		arg.RemovalReason,
	)
	return err
}

const hubDeletePost = `-- name: HubDeletePost :exec
UPDATE channel_posts SET status=$3,deleted_by=$4,deleted_at=clock_timestamp(),removal_reason=$5,updated_at=clock_timestamp() WHERE society_id=$1 AND id=$2
`

type HubDeletePostParams struct {
	SocietyID     int64   `db:"society_id" json:"society_id"`
	ID            int64   `db:"id" json:"id"`
	Status        string  `db:"status" json:"status"`
	DeletedBy     *int64  `db:"deleted_by" json:"deleted_by"`
	RemovalReason *string `db:"removal_reason" json:"removal_reason"`
}

func (q *Queries) HubDeletePost(ctx context.Context, arg HubDeletePostParams) error {
	_, err := q.db.Exec(ctx, hubDeletePost,
		arg.SocietyID,
		arg.ID,
		arg.Status,
		arg.DeletedBy,
		arg.RemovalReason,
	)
	return err
}

const hubDetach = `-- name: HubDetach :exec
DELETE FROM channel_attachments WHERE upload_id=$1
`

func (q *Queries) HubDetach(ctx context.Context, uploadID int64) error {
	_, err := q.db.Exec(ctx, hubDetach, uploadID)
	return err
}

const hubEnqueue = `-- name: HubEnqueue :exec
INSERT INTO notification_outbox(user_id,society_id,audience,event_key,payload,push_enabled)
VALUES($1,$2,'hub_member',$3,$4,$5) ON CONFLICT(user_id,event_key) DO NOTHING
`

type HubEnqueueParams struct {
	UserID      int64  `db:"user_id" json:"user_id"`
	SocietyID   int64  `db:"society_id" json:"society_id"`
	EventKey    string `db:"event_key" json:"event_key"`
	Payload     []byte `db:"payload" json:"payload"`
	PushEnabled bool   `db:"push_enabled" json:"push_enabled"`
}

func (q *Queries) HubEnqueue(ctx context.Context, arg HubEnqueueParams) error {
	_, err := q.db.Exec(ctx, hubEnqueue,
		arg.UserID,
		arg.SocietyID,
		arg.EventKey,
		arg.Payload,
		arg.PushEnabled,
	)
	return err
}

const hubFinishCleanup = `-- name: HubFinishCleanup :exec
UPDATE channel_uploads SET status='deleted',lease_until=NULL,lease_token=NULL WHERE id=$1 AND lease_token=$2 AND status='cleanup'
`

type HubFinishCleanupParams struct {
	ID         int64       `db:"id" json:"id"`
	LeaseToken pgtype.UUID `db:"lease_token" json:"lease_token"`
}

func (q *Queries) HubFinishCleanup(ctx context.Context, arg HubFinishCleanupParams) error {
	_, err := q.db.Exec(ctx, hubFinishCleanup, arg.ID, arg.LeaseToken)
	return err
}

const hubLockChannel = `-- name: HubLockChannel :one
SELECT id, society_id, type, name, description, created_at, updated_at FROM society_channels WHERE society_id=$1 AND id=$2 FOR UPDATE
`

type HubLockChannelParams struct {
	SocietyID int64 `db:"society_id" json:"society_id"`
	ID        int64 `db:"id" json:"id"`
}

func (q *Queries) HubLockChannel(ctx context.Context, arg HubLockChannelParams) (SocietyChannel, error) {
	row := q.db.QueryRow(ctx, hubLockChannel, arg.SocietyID, arg.ID)
	var i SocietyChannel
	err := row.Scan(
		&i.ID,
		&i.SocietyID,
		&i.Type,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hubLockPost = `-- name: HubLockPost :one
SELECT p.id, p.society_id, p.channel_id, p.author_id, p.title, p.body, p.category_id, p.comments_enabled, p.is_pinned, p.is_important, p.status, p.edited_at, p.removal_reason, p.deleted_at, p.deleted_by, p.created_at, p.updated_at,c.type AS channel_type FROM channel_posts p JOIN society_channels c ON c.id=p.channel_id WHERE p.society_id=$1 AND p.id=$2 FOR UPDATE OF p
`

type HubLockPostParams struct {
	SocietyID int64 `db:"society_id" json:"society_id"`
	ID        int64 `db:"id" json:"id"`
}

type HubLockPostRow struct {
	ID              int64              `db:"id" json:"id"`
	SocietyID       int64              `db:"society_id" json:"society_id"`
	ChannelID       int64              `db:"channel_id" json:"channel_id"`
	AuthorID        int64              `db:"author_id" json:"author_id"`
	Title           *string            `db:"title" json:"title"`
	Body            string             `db:"body" json:"body"`
	CategoryID      *int16             `db:"category_id" json:"category_id"`
	CommentsEnabled bool               `db:"comments_enabled" json:"comments_enabled"`
	IsPinned        bool               `db:"is_pinned" json:"is_pinned"`
	IsImportant     bool               `db:"is_important" json:"is_important"`
	Status          string             `db:"status" json:"status"`
	EditedAt        pgtype.Timestamptz `db:"edited_at" json:"edited_at"`
	RemovalReason   *string            `db:"removal_reason" json:"removal_reason"`
	DeletedAt       pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	DeletedBy       *int64             `db:"deleted_by" json:"deleted_by"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	ChannelType     string             `db:"channel_type" json:"channel_type"`
}

func (q *Queries) HubLockPost(ctx context.Context, arg HubLockPostParams) (HubLockPostRow, error) {
	row := q.db.QueryRow(ctx, hubLockPost, arg.SocietyID, arg.ID)
	var i HubLockPostRow
	err := row.Scan(
		&i.ID,
		&i.SocietyID,
		&i.ChannelID,
		&i.AuthorID,
		&i.Title,
		&i.Body,
		&i.CategoryID,
		&i.CommentsEnabled,
		&i.IsPinned,
		&i.IsImportant,
		&i.Status,
		&i.EditedAt,
		&i.RemovalReason,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ChannelType,
	)
	return i, err
}

const hubLockUpload = `-- name: HubLockUpload :one
SELECT id, society_id, uploader_id, file_id, file_path, original_filename, mime_type, file_size, width, height, status, expires_at, lease_until, lease_token, created_at FROM channel_uploads WHERE society_id=$1 AND id=$2 FOR UPDATE
`

type HubLockUploadParams struct {
	SocietyID int64 `db:"society_id" json:"society_id"`
	ID        int64 `db:"id" json:"id"`
}

func (q *Queries) HubLockUpload(ctx context.Context, arg HubLockUploadParams) (ChannelUpload, error) {
	row := q.db.QueryRow(ctx, hubLockUpload, arg.SocietyID, arg.ID)
	var i ChannelUpload
	err := row.Scan(
		&i.ID,
		&i.SocietyID,
		&i.UploaderID,
		&i.FileID,
		&i.FilePath,
		&i.OriginalFilename,
		&i.MimeType,
		&i.FileSize,
		&i.Width,
		&i.Height,
		&i.Status,
		&i.ExpiresAt,
		&i.LeaseUntil,
		&i.LeaseToken,
		&i.CreatedAt,
	)
	return i, err
}

const hubPinnedIDs = `-- name: HubPinnedIDs :many
SELECT id FROM channel_posts WHERE society_id=$1 AND channel_id=$2 AND status='active' AND is_pinned ORDER BY created_at DESC,id DESC
`

type HubPinnedIDsParams struct {
	SocietyID int64 `db:"society_id" json:"society_id"`
	ChannelID int64 `db:"channel_id" json:"channel_id"`
}

func (q *Queries) HubPinnedIDs(ctx context.Context, arg HubPinnedIDsParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, hubPinnedIDs, arg.SocietyID, arg.ChannelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hubPost = `-- name: HubPost :one
SELECT p.id, p.society_id, p.channel_id, p.author_id, p.title, p.body, p.category_id, p.comments_enabled, p.is_pinned, p.is_important, p.status, p.edited_at, p.removal_reason, p.deleted_at, p.deleted_by, p.created_at, p.updated_at,c.type AS channel_type FROM channel_posts p JOIN society_channels c ON c.id=p.channel_id WHERE p.society_id=$1 AND p.id=$2
`

type HubPostParams struct {
	SocietyID int64 `db:"society_id" json:"society_id"`
	ID        int64 `db:"id" json:"id"`
}

type HubPostRow struct {
	ID              int64              `db:"id" json:"id"`
	SocietyID       int64              `db:"society_id" json:"society_id"`
	ChannelID       int64              `db:"channel_id" json:"channel_id"`
	AuthorID        int64              `db:"author_id" json:"author_id"`
	Title           *string            `db:"title" json:"title"`
	Body            string             `db:"body" json:"body"`
	CategoryID      *int16             `db:"category_id" json:"category_id"`
	CommentsEnabled bool               `db:"comments_enabled" json:"comments_enabled"`
	IsPinned        bool               `db:"is_pinned" json:"is_pinned"`
	IsImportant     bool               `db:"is_important" json:"is_important"`
	Status          string             `db:"status" json:"status"`
	EditedAt        pgtype.Timestamptz `db:"edited_at" json:"edited_at"`
	RemovalReason   *string            `db:"removal_reason" json:"removal_reason"`
	DeletedAt       pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	DeletedBy       *int64             `db:"deleted_by" json:"deleted_by"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	ChannelType     string             `db:"channel_type" json:"channel_type"`
}

func (q *Queries) HubPost(ctx context.Context, arg HubPostParams) (HubPostRow, error) {
	row := q.db.QueryRow(ctx, hubPost, arg.SocietyID, arg.ID)
	var i HubPostRow
	err := row.Scan(
		&i.ID,
		&i.SocietyID,
		&i.ChannelID,
		&i.AuthorID,
		&i.Title,
		&i.Body,
		&i.CategoryID,
		&i.CommentsEnabled,
		&i.IsPinned,
		&i.IsImportant,
		&i.Status,
		&i.EditedAt,
		&i.RemovalReason,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ChannelType,
	)
	return i, err
}

const hubPostIDs = `-- name: HubPostIDs :many
SELECT id FROM channel_posts WHERE society_id=$1 AND channel_id=$2 AND status='active'
AND ($3::smallint IS NULL OR category_id=$3)
AND ($4::timestamptz IS NULL OR (created_at,id)<($4,$5::bigint))
ORDER BY created_at DESC,id DESC LIMIT $6
`

type HubPostIDsParams struct {
	SocietyID  int64              `db:"society_id" json:"society_id"`
	ChannelID  int64              `db:"channel_id" json:"channel_id"`
	CategoryID *int16             `db:"category_id" json:"category_id"`
	BeforeAt   pgtype.Timestamptz `db:"before_at" json:"before_at"`
	BeforeID   int64              `db:"before_id" json:"before_id"`
	PageLimit  int32              `db:"page_limit" json:"page_limit"`
}

func (q *Queries) HubPostIDs(ctx context.Context, arg HubPostIDsParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, hubPostIDs,
		arg.SocietyID,
		arg.ChannelID,
		arg.CategoryID,
		arg.BeforeAt,
		arg.BeforeID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hubPostRate = `-- name: HubPostRate :one
SELECT count(*)::bigint AS count,min(created_at)::timestamptz AS oldest FROM channel_posts
WHERE society_id=$1 AND author_id=$2 AND created_at>clock_timestamp()-$3::int*interval '1 second'
`

type HubPostRateParams struct {
	SocietyID     int64 `db:"society_id" json:"society_id"`
	AuthorID      int64 `db:"author_id" json:"author_id"`
	WindowSeconds int32 `db:"window_seconds" json:"window_seconds"`
}

type HubPostRateRow struct {
	Count  int64              `db:"count" json:"count"`
	Oldest pgtype.Timestamptz `db:"oldest" json:"oldest"`
}

func (q *Queries) HubPostRate(ctx context.Context, arg HubPostRateParams) (HubPostRateRow, error) {
	row := q.db.QueryRow(ctx, hubPostRate, arg.SocietyID, arg.AuthorID, arg.WindowSeconds)
	var i HubPostRateRow
	err := row.Scan(&i.Count, &i.Oldest)
	return i, err
}

const hubPostView = `-- name: HubPostView :one
SELECT jsonb_build_object('id',p.id,'society_id',p.society_id,'channel_id',p.channel_id,'author',jsonb_build_object('id',u.id,'name',u.full_name),
 'title',p.title,'body',p.body,'category_id',p.category_id,'comments_enabled',p.comments_enabled,'is_pinned',p.is_pinned,'is_important',p.is_important,
 'status',p.status,'created_at',p.created_at,'updated_at',p.updated_at,'edited_at',p.edited_at,
 'reply_count',(SELECT count(*) FROM channel_comments c WHERE c.post_id=p.id AND c.status='active'),
 'reactions',COALESCE((SELECT jsonb_object_agg(x.reaction_type,x.n) FROM (SELECT reaction_type,count(*) n FROM channel_reactions WHERE post_id=p.id GROUP BY reaction_type) x),'{}'),
 'my_reactions',COALESCE((SELECT jsonb_agg(reaction_type ORDER BY reaction_type) FROM channel_reactions cr WHERE cr.post_id=p.id AND cr.user_id=$1),'[]'),
 'attachment_ids',COALESCE((SELECT jsonb_agg(upload_id ORDER BY id) FROM channel_attachments WHERE post_id=p.id),'[]')) AS data
FROM channel_posts p JOIN users u ON u.id=p.author_id WHERE p.society_id=$2 AND p.id=$3 AND p.status='active'
`

type HubPostViewParams struct {
	UserID    int64 `db:"user_id" json:"user_id"`
	SocietyID int64 `db:"society_id" json:"society_id"`
	ID        int64 `db:"id" json:"id"`
}

func (q *Queries) HubPostView(ctx context.Context, arg HubPostViewParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, hubPostView, arg.UserID, arg.SocietyID, arg.ID)
	var data []byte
	err := row.Scan(&data)
	return data, err
}

const hubProvisionChannels = `-- name: HubProvisionChannels :exec
INSERT INTO society_channels(society_id,type,name,description)
VALUES ($1,'announcement','Announcements','Official society updates'),($1,'community','Community','Connect with neighbours')
ON CONFLICT(society_id,type) DO NOTHING
`

func (q *Queries) HubProvisionChannels(ctx context.Context, societyID int64) error {
	_, err := q.db.Exec(ctx, hubProvisionChannels, societyID)
	return err
}

const hubQueueUploadCleanup = `-- name: HubQueueUploadCleanup :exec
UPDATE channel_uploads SET status='cleanup',expires_at=clock_timestamp() WHERE id=$1 AND status IN ('pending','claimed')
`

func (q *Queries) HubQueueUploadCleanup(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, hubQueueUploadCleanup, id)
	return err
}

const hubRead = `-- name: HubRead :exec
INSERT INTO channel_read_states(user_id,channel_id,last_read_post_id,last_read_created_at,last_read_at)
SELECT $1,p.channel_id,p.id,p.created_at,clock_timestamp() FROM channel_posts p
WHERE p.society_id=$2 AND p.channel_id=$3 AND p.id=$4
ON CONFLICT(user_id,channel_id) DO UPDATE SET last_read_post_id=excluded.last_read_post_id,last_read_created_at=excluded.last_read_created_at,last_read_at=excluded.last_read_at,updated_at=clock_timestamp()
WHERE (excluded.last_read_created_at,excluded.last_read_post_id)>(channel_read_states.last_read_created_at,channel_read_states.last_read_post_id)
`

type HubReadParams struct {
	UserID    int64 `db:"user_id" json:"user_id"`
	SocietyID int64 `db:"society_id" json:"society_id"`
	ChannelID int64 `db:"channel_id" json:"channel_id"`
	PostID    int64 `db:"post_id" json:"post_id"`
}

func (q *Queries) HubRead(ctx context.Context, arg HubReadParams) error {
	_, err := q.db.Exec(ctx, hubRead,
		arg.UserID,
		arg.SocietyID,
		arg.ChannelID,
		arg.PostID,
	)
	return err
}

const hubRemoveReaction = `-- name: HubRemoveReaction :exec
DELETE FROM channel_reactions WHERE user_id=$1 AND post_id IS NOT DISTINCT FROM $2::bigint
AND comment_id IS NOT DISTINCT FROM $3::bigint AND reaction_type=$4
`

type HubRemoveReactionParams struct {
	UserID       int64  `db:"user_id" json:"user_id"`
	PostID       *int64 `db:"post_id" json:"post_id"`
	CommentID    *int64 `db:"comment_id" json:"comment_id"`
	ReactionType string `db:"reaction_type" json:"reaction_type"`
}

func (q *Queries) HubRemoveReaction(ctx context.Context, arg HubRemoveReactionParams) error {
	_, err := q.db.Exec(ctx, hubRemoveReaction,
		arg.UserID,
		arg.PostID,
		arg.CommentID,
		arg.ReactionType,
	)
	return err
}

const hubReport = `-- name: HubReport :one
INSERT INTO channel_reports(post_id,reporter_id,reason) VALUES($1,$2,$3)
ON CONFLICT(post_id,reporter_id) DO UPDATE SET reason=channel_reports.reason RETURNING id, post_id, reporter_id, reason, status, reviewer_id, reviewed_at, resolution_note, created_at
`

type HubReportParams struct {
	PostID     int64  `db:"post_id" json:"post_id"`
	ReporterID int64  `db:"reporter_id" json:"reporter_id"`
	Reason     string `db:"reason" json:"reason"`
}

func (q *Queries) HubReport(ctx context.Context, arg HubReportParams) (ChannelReport, error) {
	row := q.db.QueryRow(ctx, hubReport, arg.PostID, arg.ReporterID, arg.Reason)
	var i ChannelReport
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.ReporterID,
		&i.Reason,
		&i.Status,
		&i.ReviewerID,
		&i.ReviewedAt,
		&i.ResolutionNote,
		&i.CreatedAt,
	)
	return i, err
}

const hubReportByID = `-- name: HubReportByID :one
SELECT r.id, r.post_id, r.reporter_id, r.reason, r.status, r.reviewer_id, r.reviewed_at, r.resolution_note, r.created_at FROM channel_reports r JOIN channel_posts p ON p.id=r.post_id WHERE p.society_id=$1 AND r.id=$2
`

type HubReportByIDParams struct {
	SocietyID int64 `db:"society_id" json:"society_id"`
	ID        int64 `db:"id" json:"id"`
}

func (q *Queries) HubReportByID(ctx context.Context, arg HubReportByIDParams) (ChannelReport, error) {
	row := q.db.QueryRow(ctx, hubReportByID, arg.SocietyID, arg.ID)
	var i ChannelReport
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.ReporterID,
		&i.Reason,
		&i.Status,
		&i.ReviewerID,
		&i.ReviewedAt,
		&i.ResolutionNote,
		&i.CreatedAt,
	)
	return i, err
}

const hubReports = `-- name: HubReports :many
SELECT r.id, r.post_id, r.reporter_id, r.reason, r.status, r.reviewer_id, r.reviewed_at, r.resolution_note, r.created_at FROM channel_reports r JOIN channel_posts p ON p.id=r.post_id WHERE p.society_id=$1
AND ($2::text='' OR r.status=$2) AND r.id>$3
ORDER BY r.id LIMIT $4
`

type HubReportsParams struct {
	SocietyID int64  `db:"society_id" json:"society_id"`
	Status    string `db:"status" json:"status"`
	AfterID   int64  `db:"after_id" json:"after_id"`
	PageLimit int32  `db:"page_limit" json:"page_limit"`
}

func (q *Queries) HubReports(ctx context.Context, arg HubReportsParams) ([]ChannelReport, error) {
	rows, err := q.db.Query(ctx, hubReports,
		arg.SocietyID,
		arg.Status,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChannelReport{}
	for rows.Next() {
		var i ChannelReport
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.ReporterID,
			&i.Reason,
			&i.Status,
			&i.ReviewerID,
			&i.ReviewedAt,
			&i.ResolutionNote,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hubResidents = `-- name: HubResidents :many
SELECT DISTINCT m.user_id FROM society_members m JOIN users u ON u.id=m.user_id
WHERE m.society_id=$1 AND m.role='resident' AND m.status='active' AND u.is_active AND NOT u.is_blocked AND u.deleted_at IS NULL
`

func (q *Queries) HubResidents(ctx context.Context, societyID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, hubResidents, societyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var user_id int64
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hubResolvePostReports = `-- name: HubResolvePostReports :exec
UPDATE channel_reports SET status='actioned',reviewer_id=$2,reviewed_at=clock_timestamp(),resolution_note=$3 WHERE post_id=$1 AND status='pending'
`

type HubResolvePostReportsParams struct {
	PostID         int64   `db:"post_id" json:"post_id"`
	ReviewerID     *int64  `db:"reviewer_id" json:"reviewer_id"`
	ResolutionNote *string `db:"resolution_note" json:"resolution_note"`
}

func (q *Queries) HubResolvePostReports(ctx context.Context, arg HubResolvePostReportsParams) error {
	_, err := q.db.Exec(ctx, hubResolvePostReports, arg.PostID, arg.ReviewerID, arg.ResolutionNote)
	return err
}

const hubResolveReport = `-- name: HubResolveReport :exec
UPDATE channel_reports SET status=$2,reviewer_id=$3,reviewed_at=clock_timestamp(),resolution_note=$4 WHERE id=$1 AND status='pending'
`

type HubResolveReportParams struct {
	ID             int64   `db:"id" json:"id"`
	Status         string  `db:"status" json:"status"`
	ReviewerID     *int64  `db:"reviewer_id" json:"reviewer_id"`
	ResolutionNote *string `db:"resolution_note" json:"resolution_note"`
}

func (q *Queries) HubResolveReport(ctx context.Context, arg HubResolveReportParams) error {
	_, err := q.db.Exec(ctx, hubResolveReport,
		arg.ID,
		arg.Status,
		arg.ReviewerID,
		arg.ResolutionNote,
	)
	return err
}

const hubRole = `-- name: HubRole :one
SELECT m.role::text FROM society_members m JOIN societies s ON s.id=m.society_id JOIN users u ON u.id=m.user_id
WHERE m.society_id=$1 AND m.user_id=$2 AND m.status='active' AND m.role IN ('owner','admin','resident')
AND s.status='active' AND s.deleted_at IS NULL AND u.is_active AND NOT u.is_blocked AND u.deleted_at IS NULL
ORDER BY CASE m.role WHEN 'owner' THEN 0 WHEN 'admin' THEN 1 ELSE 2 END LIMIT 1
`

type HubRoleParams struct {
	SocietyID int64 `db:"society_id" json:"society_id"`
	UserID    int64 `db:"user_id" json:"user_id"`
}

func (q *Queries) HubRole(ctx context.Context, arg HubRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, hubRole, arg.SocietyID, arg.UserID)
	var m_role string
	err := row.Scan(&m_role)
	return m_role, err
}

const hubUpdateComment = `-- name: HubUpdateComment :exec
UPDATE channel_comments SET body=$3,edited_at=clock_timestamp(),updated_at=clock_timestamp() WHERE id=$1 AND post_id=$2
`

type HubUpdateCommentParams struct {
	ID     int64  `db:"id" json:"id"`
	PostID int64  `db:"post_id" json:"post_id"`
	Body   string `db:"body" json:"body"`
}

func (q *Queries) HubUpdateComment(ctx context.Context, arg HubUpdateCommentParams) error {
	_, err := q.db.Exec(ctx, hubUpdateComment, arg.ID, arg.PostID, arg.Body)
	return err
}

const hubUpdatePost = `-- name: HubUpdatePost :exec
UPDATE channel_posts SET title=$3,body=$4,category_id=$5,comments_enabled=$6,is_pinned=$7,is_important=$8,edited_at=clock_timestamp(),updated_at=clock_timestamp()
WHERE society_id=$1 AND id=$2
`

type HubUpdatePostParams struct {
	SocietyID       int64   `db:"society_id" json:"society_id"`
	ID              int64   `db:"id" json:"id"`
	Title           *string `db:"title" json:"title"`
	Body            string  `db:"body" json:"body"`
	CategoryID      *int16  `db:"category_id" json:"category_id"`
	CommentsEnabled bool    `db:"comments_enabled" json:"comments_enabled"`
	IsPinned        bool    `db:"is_pinned" json:"is_pinned"`
	IsImportant     bool    `db:"is_important" json:"is_important"`
}

func (q *Queries) HubUpdatePost(ctx context.Context, arg HubUpdatePostParams) error {
	_, err := q.db.Exec(ctx, hubUpdatePost,
		arg.SocietyID,
		arg.ID,
		arg.Title,
		arg.Body,
		arg.CategoryID,
		arg.CommentsEnabled,
		arg.IsPinned,
		arg.IsImportant,
	)
	return err
}

const hubUpload = `-- name: HubUpload :one
SELECT id, society_id, uploader_id, file_id, file_path, original_filename, mime_type, file_size, width, height, status, expires_at, lease_until, lease_token, created_at FROM channel_uploads WHERE society_id=$1 AND id=$2
`

type HubUploadParams struct {
	SocietyID int64 `db:"society_id" json:"society_id"`
	ID        int64 `db:"id" json:"id"`
}

func (q *Queries) HubUpload(ctx context.Context, arg HubUploadParams) (ChannelUpload, error) {
	row := q.db.QueryRow(ctx, hubUpload, arg.SocietyID, arg.ID)
	var i ChannelUpload
	err := row.Scan(
		&i.ID,
		&i.SocietyID,
		&i.UploaderID,
		&i.FileID,
		&i.FilePath,
		&i.OriginalFilename,
		&i.MimeType,
		&i.FileSize,
		&i.Width,
		&i.Height,
		&i.Status,
		&i.ExpiresAt,
		&i.LeaseUntil,
		&i.LeaseToken,
		&i.CreatedAt,
	)
	return i, err
}

const hubUploadByFile = `-- name: HubUploadByFile :one
SELECT id, society_id, uploader_id, file_id, file_path, original_filename, mime_type, file_size, width, height, status, expires_at, lease_until, lease_token, created_at FROM channel_uploads WHERE file_id=$1
`

func (q *Queries) HubUploadByFile(ctx context.Context, fileID string) (ChannelUpload, error) {
	row := q.db.QueryRow(ctx, hubUploadByFile, fileID)
	var i ChannelUpload
	err := row.Scan(
		&i.ID,
		&i.SocietyID,
		&i.UploaderID,
		&i.FileID,
		&i.FilePath,
		&i.OriginalFilename,
		&i.MimeType,
		&i.FileSize,
		&i.Width,
		&i.Height,
		&i.Status,
		&i.ExpiresAt,
		&i.LeaseUntil,
		&i.LeaseToken,
		&i.CreatedAt,
	)
	return i, err
}
