// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: images.sql

package db

import (
	"context"
)

const getUserImage = `-- name: GetUserImage :one
SELECT avatar_url, avatar_imagekit_file_id, avatar_imagekit_file_path FROM users WHERE id = $1 AND deleted_at IS NULL
`

type GetUserImageRow struct {
	AvatarUrl              *string `db:"avatar_url" json:"avatar_url"`
	AvatarImagekitFileID   *string `db:"avatar_imagekit_file_id" json:"avatar_imagekit_file_id"`
	AvatarImagekitFilePath *string `db:"avatar_imagekit_file_path" json:"avatar_imagekit_file_path"`
}

func (q *Queries) GetUserImage(ctx context.Context, id int64) (GetUserImageRow, error) {
	row := q.db.QueryRow(ctx, getUserImage, id)
	var i GetUserImageRow
	err := row.Scan(&i.AvatarUrl, &i.AvatarImagekitFileID, &i.AvatarImagekitFilePath)
	return i, err
}

const getVisitorImage = `-- name: GetVisitorImage :one
SELECT photo_url, photo_imagekit_file_id, photo_imagekit_file_path FROM visitors WHERE id = $1
`

type GetVisitorImageRow struct {
	PhotoUrl              *string `db:"photo_url" json:"photo_url"`
	PhotoImagekitFileID   *string `db:"photo_imagekit_file_id" json:"photo_imagekit_file_id"`
	PhotoImagekitFilePath *string `db:"photo_imagekit_file_path" json:"photo_imagekit_file_path"`
}

func (q *Queries) GetVisitorImage(ctx context.Context, id int64) (GetVisitorImageRow, error) {
	row := q.db.QueryRow(ctx, getVisitorImage, id)
	var i GetVisitorImageRow
	err := row.Scan(&i.PhotoUrl, &i.PhotoImagekitFileID, &i.PhotoImagekitFilePath)
	return i, err
}

const lockUserImage = `-- name: LockUserImage :one
SELECT avatar_url, avatar_imagekit_file_id, avatar_imagekit_file_path FROM users WHERE id = $1 AND deleted_at IS NULL FOR UPDATE
`

type LockUserImageRow struct {
	AvatarUrl              *string `db:"avatar_url" json:"avatar_url"`
	AvatarImagekitFileID   *string `db:"avatar_imagekit_file_id" json:"avatar_imagekit_file_id"`
	AvatarImagekitFilePath *string `db:"avatar_imagekit_file_path" json:"avatar_imagekit_file_path"`
}

func (q *Queries) LockUserImage(ctx context.Context, id int64) (LockUserImageRow, error) {
	row := q.db.QueryRow(ctx, lockUserImage, id)
	var i LockUserImageRow
	err := row.Scan(&i.AvatarUrl, &i.AvatarImagekitFileID, &i.AvatarImagekitFilePath)
	return i, err
}

const lockVisitorImage = `-- name: LockVisitorImage :one
SELECT photo_url, photo_imagekit_file_id, photo_imagekit_file_path FROM visitors WHERE id = $1 FOR UPDATE
`

type LockVisitorImageRow struct {
	PhotoUrl              *string `db:"photo_url" json:"photo_url"`
	PhotoImagekitFileID   *string `db:"photo_imagekit_file_id" json:"photo_imagekit_file_id"`
	PhotoImagekitFilePath *string `db:"photo_imagekit_file_path" json:"photo_imagekit_file_path"`
}

func (q *Queries) LockVisitorImage(ctx context.Context, id int64) (LockVisitorImageRow, error) {
	row := q.db.QueryRow(ctx, lockVisitorImage, id)
	var i LockVisitorImageRow
	err := row.Scan(&i.PhotoUrl, &i.PhotoImagekitFileID, &i.PhotoImagekitFilePath)
	return i, err
}

const setUserImage = `-- name: SetUserImage :execrows
UPDATE users SET avatar_url = $1, avatar_imagekit_file_id = $2,
 avatar_imagekit_file_path = $3, updated_at = NOW() WHERE id = $4 AND deleted_at IS NULL
`

type SetUserImageParams struct {
	Url      *string `db:"url" json:"url"`
	FileID   *string `db:"file_id" json:"file_id"`
	FilePath *string `db:"file_path" json:"file_path"`
	ID       int64   `db:"id" json:"id"`
}

func (q *Queries) SetUserImage(ctx context.Context, arg SetUserImageParams) (int64, error) {
	result, err := q.db.Exec(ctx, setUserImage,
		arg.Url,
		arg.FileID,
		arg.FilePath,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setVisitorImage = `-- name: SetVisitorImage :execrows
UPDATE visitors SET photo_url = $1, photo_imagekit_file_id = $2,
 photo_imagekit_file_path = $3, updated_at = NOW() WHERE id = $4
`

type SetVisitorImageParams struct {
	Url      *string `db:"url" json:"url"`
	FileID   *string `db:"file_id" json:"file_id"`
	FilePath *string `db:"file_path" json:"file_path"`
	ID       int64   `db:"id" json:"id"`
}

func (q *Queries) SetVisitorImage(ctx context.Context, arg SetVisitorImageParams) (int64, error) {
	result, err := q.db.Exec(ctx, setVisitorImage,
		arg.Url,
		arg.FileID,
		arg.FilePath,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
