// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimMonthlyVisitorReportDelivery = `-- name: ClaimMonthlyVisitorReportDelivery :one
UPDATE monthly_visitor_report_deliveries
SET status = 'processing',
    attempt_count = attempt_count + 1,
    processing_until = $1,
    sent_at = CASE WHEN $2::boolean THEN NULL ELSE sent_at END,
    last_error = NULL,
    updated_at = NOW()
WHERE society_id = $3
  AND report_month = $4
  AND (sent_at IS NULL OR $2::boolean)
  AND (processing_until IS NULL OR processing_until <= NOW())
RETURNING id, society_id, report_month, status, attempt_count, processing_until, recipients, provider_message_id, last_error, sent_at, created_at, updated_at
`

type ClaimMonthlyVisitorReportDeliveryParams struct {
	ProcessingUntil pgtype.Timestamptz `db:"processing_until" json:"processing_until"`
	AllowResend     bool               `db:"allow_resend" json:"allow_resend"`
	SocietyID       int64              `db:"society_id" json:"society_id"`
	ReportMonth     pgtype.Date        `db:"report_month" json:"report_month"`
}

func (q *Queries) ClaimMonthlyVisitorReportDelivery(ctx context.Context, arg ClaimMonthlyVisitorReportDeliveryParams) (MonthlyVisitorReportDelivery, error) {
	row := q.db.QueryRow(ctx, claimMonthlyVisitorReportDelivery,
		arg.ProcessingUntil,
		arg.AllowResend,
		arg.SocietyID,
		arg.ReportMonth,
	)
	var i MonthlyVisitorReportDelivery
	err := row.Scan(
		&i.ID,
		&i.SocietyID,
		&i.ReportMonth,
		&i.Status,
		&i.AttemptCount,
		&i.ProcessingUntil,
		&i.Recipients,
		&i.ProviderMessageID,
		&i.LastError,
		&i.SentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const completeMonthlyVisitorReportDelivery = `-- name: CompleteMonthlyVisitorReportDelivery :execrows
UPDATE monthly_visitor_report_deliveries
SET status = 'sent',
    recipients = $1,
    provider_message_id = $2,
    sent_at = NOW(),
    processing_until = NULL,
    last_error = NULL,
    updated_at = NOW()
WHERE society_id = $3
  AND report_month = $4
  AND (sent_at IS NULL OR $5::boolean)
`

type CompleteMonthlyVisitorReportDeliveryParams struct {
	Recipients        []string    `db:"recipients" json:"recipients"`
	ProviderMessageID *string     `db:"provider_message_id" json:"provider_message_id"`
	SocietyID         int64       `db:"society_id" json:"society_id"`
	ReportMonth       pgtype.Date `db:"report_month" json:"report_month"`
	AllowResend       bool        `db:"allow_resend" json:"allow_resend"`
}

func (q *Queries) CompleteMonthlyVisitorReportDelivery(ctx context.Context, arg CompleteMonthlyVisitorReportDeliveryParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeMonthlyVisitorReportDelivery,
		arg.Recipients,
		arg.ProviderMessageID,
		arg.SocietyID,
		arg.ReportMonth,
		arg.AllowResend,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const completeVisitorImageDeletion = `-- name: CompleteVisitorImageDeletion :exec
DELETE FROM visitor_image_deletions WHERE id = $1
`

func (q *Queries) CompleteVisitorImageDeletion(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, completeVisitorImageDeletion, id)
	return err
}

const deleteFlatMemberInvitesByIDs = `-- name: DeleteFlatMemberInvitesByIDs :execrows
DELETE FROM flat_member_invites
WHERE id = ANY($1::bigint[])
`

func (q *Queries) DeleteFlatMemberInvitesByIDs(ctx context.Context, ids []int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFlatMemberInvitesByIDs, ids)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteNotificationsBatch = `-- name: DeleteNotificationsBatch :execrows
WITH candidates AS (
    SELECT n.id
    FROM notifications n
    WHERE n.created_at < $1
    ORDER BY n.created_at, n.id
    LIMIT $2
    FOR UPDATE SKIP LOCKED
)
DELETE FROM notifications n
USING candidates c
WHERE n.id = c.id
`

type DeleteNotificationsBatchParams struct {
	Cutoff    pgtype.Timestamptz `db:"cutoff" json:"cutoff"`
	BatchSize int32              `db:"batch_size" json:"batch_size"`
}

func (q *Queries) DeleteNotificationsBatch(ctx context.Context, arg DeleteNotificationsBatchParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteNotificationsBatch, arg.Cutoff, arg.BatchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteShortLinksForResources = `-- name: DeleteShortLinksForResources :execrows
DELETE FROM short_links
WHERE resource_type = $1
  AND resource_id = ANY($2::bigint[])
`

type DeleteShortLinksForResourcesParams struct {
	ResourceType string  `db:"resource_type" json:"resource_type"`
	ResourceIds  []int64 `db:"resource_ids" json:"resource_ids"`
}

func (q *Queries) DeleteShortLinksForResources(ctx context.Context, arg DeleteShortLinksForResourcesParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteShortLinksForResources, arg.ResourceType, arg.ResourceIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUnreferencedVisitors = `-- name: DeleteUnreferencedVisitors :many
DELETE FROM visitors v
WHERE v.id = ANY($1::bigint[])
  AND NOT EXISTS (SELECT 1 FROM visitor_entries ve WHERE ve.visitor_id = v.id)
RETURNING v.id, v.photo_url, v.photo_imagekit_file_id
`

type DeleteUnreferencedVisitorsRow struct {
	ID                  int64   `db:"id" json:"id"`
	PhotoUrl            *string `db:"photo_url" json:"photo_url"`
	PhotoImagekitFileID *string `db:"photo_imagekit_file_id" json:"photo_imagekit_file_id"`
}

func (q *Queries) DeleteUnreferencedVisitors(ctx context.Context, ids []int64) ([]DeleteUnreferencedVisitorsRow, error) {
	rows, err := q.db.Query(ctx, deleteUnreferencedVisitors, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeleteUnreferencedVisitorsRow{}
	for rows.Next() {
		var i DeleteUnreferencedVisitorsRow
		if err := rows.Scan(&i.ID, &i.PhotoUrl, &i.PhotoImagekitFileID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteVerificationsBatch = `-- name: DeleteVerificationsBatch :execrows
WITH candidates AS (
    SELECT uv.id
    FROM user_verifications uv
    WHERE uv.is_used = TRUE OR uv.expires_at < NOW()
    ORDER BY uv.expires_at, uv.id
    LIMIT $1
    FOR UPDATE SKIP LOCKED
)
DELETE FROM user_verifications uv
USING candidates c
WHERE uv.id = c.id
`

func (q *Queries) DeleteVerificationsBatch(ctx context.Context, batchSize int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteVerificationsBatch, batchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteVisitorEntriesBatch = `-- name: DeleteVisitorEntriesBatch :many
WITH candidates AS (
    SELECT ve.id
    FROM visitor_entries ve
    WHERE ve.society_id = $1
      AND ve.created_at >= $2
      AND ve.created_at < $3
      AND ve.updated_at < $4
      AND ve.status IN ('rejected', 'checked_out', 'cancelled', 'expired', 'auto_closed')
      AND EXISTS (
          SELECT 1
          FROM monthly_visitor_report_deliveries d
          WHERE d.society_id = ve.society_id
            AND d.report_month = $5
            AND d.sent_at IS NOT NULL
      )
    ORDER BY ve.updated_at, ve.id
    LIMIT $6
    FOR UPDATE SKIP LOCKED
)
DELETE FROM visitor_entries ve
USING candidates c
WHERE ve.id = c.id
RETURNING ve.visitor_id
`

type DeleteVisitorEntriesBatchParams struct {
	SocietyID   int64              `db:"society_id" json:"society_id"`
	PeriodStart pgtype.Timestamptz `db:"period_start" json:"period_start"`
	PeriodEnd   pgtype.Timestamptz `db:"period_end" json:"period_end"`
	Cutoff      pgtype.Timestamptz `db:"cutoff" json:"cutoff"`
	ReportMonth pgtype.Date        `db:"report_month" json:"report_month"`
	BatchSize   int32              `db:"batch_size" json:"batch_size"`
}

func (q *Queries) DeleteVisitorEntriesBatch(ctx context.Context, arg DeleteVisitorEntriesBatchParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, deleteVisitorEntriesBatch,
		arg.SocietyID,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.Cutoff,
		arg.ReportMonth,
		arg.BatchSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var visitor_id int64
		if err := rows.Scan(&visitor_id); err != nil {
			return nil, err
		}
		items = append(items, visitor_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteVisitorInvitesByIDs = `-- name: DeleteVisitorInvitesByIDs :execrows
DELETE FROM visitor_invites vi
WHERE vi.id = ANY($1::bigint[])
  AND NOT EXISTS (
      SELECT 1 FROM visitor_entries ve WHERE ve.invite_id = vi.id
  )
`

func (q *Queries) DeleteVisitorInvitesByIDs(ctx context.Context, ids []int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteVisitorInvitesByIDs, ids)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const ensureMonthlyVisitorReportDelivery = `-- name: EnsureMonthlyVisitorReportDelivery :exec
INSERT INTO monthly_visitor_report_deliveries (society_id, report_month)
VALUES ($1, $2)
ON CONFLICT (society_id, report_month) DO NOTHING
`

type EnsureMonthlyVisitorReportDeliveryParams struct {
	SocietyID   int64       `db:"society_id" json:"society_id"`
	ReportMonth pgtype.Date `db:"report_month" json:"report_month"`
}

func (q *Queries) EnsureMonthlyVisitorReportDelivery(ctx context.Context, arg EnsureMonthlyVisitorReportDeliveryParams) error {
	_, err := q.db.Exec(ctx, ensureMonthlyVisitorReportDelivery, arg.SocietyID, arg.ReportMonth)
	return err
}

const expireApprovedVisitorEntriesForJob = `-- name: ExpireApprovedVisitorEntriesForJob :execrows
UPDATE visitor_entries
SET status = 'expired', updated_at = NOW()
WHERE status = 'approved'
  AND checked_in_at IS NULL
  AND (
    (expected_checkout_at IS NOT NULL AND expected_checkout_at < NOW())
    OR (qr_expires_at IS NOT NULL AND qr_expires_at < NOW())
  )
`

func (q *Queries) ExpireApprovedVisitorEntriesForJob(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, expireApprovedVisitorEntriesForJob)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const expireFlatMemberInvitesForJob = `-- name: ExpireFlatMemberInvitesForJob :execrows
UPDATE flat_member_invites
SET status = 'expired', updated_at = NOW()
WHERE status = 'pending'
  AND expires_at < NOW()
`

func (q *Queries) ExpireFlatMemberInvitesForJob(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, expireFlatMemberInvitesForJob)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const expireSubscriptionsForJob = `-- name: ExpireSubscriptionsForJob :execrows
UPDATE society_subscriptions
SET status = 'expired', expired_at = NOW(), updated_at = NOW()
WHERE status IN ('trial', 'active')
  AND (
    (ends_at IS NOT NULL AND ends_at <= NOW())
    OR (status = 'trial' AND trial_ends_at IS NOT NULL AND trial_ends_at <= NOW())
  )
`

func (q *Queries) ExpireSubscriptionsForJob(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, expireSubscriptionsForJob)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const expireVisitorInvitesForJob = `-- name: ExpireVisitorInvitesForJob :execrows
UPDATE visitor_invites
SET status = 'expired', updated_at = NOW()
WHERE status = 'active'
  AND expires_at < NOW()
`

func (q *Queries) ExpireVisitorInvitesForJob(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, expireVisitorInvitesForJob)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const expireWaitingVisitorEntriesForJob = `-- name: ExpireWaitingVisitorEntriesForJob :execrows
UPDATE visitor_entries
SET status = 'expired', updated_at = NOW()
WHERE status = 'waiting_approval'
  AND created_at < NOW() - INTERVAL '48 hours'
`

func (q *Queries) ExpireWaitingVisitorEntriesForJob(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, expireWaitingVisitorEntriesForJob)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const failMonthlyVisitorReportDelivery = `-- name: FailMonthlyVisitorReportDelivery :execrows
UPDATE monthly_visitor_report_deliveries
SET status = 'failed',
    recipients = $1,
    processing_until = NULL,
    last_error = $2,
    updated_at = NOW()
WHERE society_id = $3
  AND report_month = $4
  AND (sent_at IS NULL OR $5::boolean)
`

type FailMonthlyVisitorReportDeliveryParams struct {
	Recipients  []string    `db:"recipients" json:"recipients"`
	LastError   *string     `db:"last_error" json:"last_error"`
	SocietyID   int64       `db:"society_id" json:"society_id"`
	ReportMonth pgtype.Date `db:"report_month" json:"report_month"`
	AllowResend bool        `db:"allow_resend" json:"allow_resend"`
}

func (q *Queries) FailMonthlyVisitorReportDelivery(ctx context.Context, arg FailMonthlyVisitorReportDeliveryParams) (int64, error) {
	result, err := q.db.Exec(ctx, failMonthlyVisitorReportDelivery,
		arg.Recipients,
		arg.LastError,
		arg.SocietyID,
		arg.ReportMonth,
		arg.AllowResend,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getEarliestVisitorEntryCreatedAt = `-- name: GetEarliestVisitorEntryCreatedAt :one
SELECT created_at
FROM visitor_entries
WHERE society_id = $1
ORDER BY created_at, id
LIMIT 1
`

func (q *Queries) GetEarliestVisitorEntryCreatedAt(ctx context.Context, societyID int64) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getEarliestVisitorEntryCreatedAt, societyID)
	var created_at pgtype.Timestamptz
	err := row.Scan(&created_at)
	return created_at, err
}

const getMonthlyVisitorReportDeliveryForUpdate = `-- name: GetMonthlyVisitorReportDeliveryForUpdate :one
SELECT id, society_id, report_month, status, attempt_count, processing_until, recipients, provider_message_id, last_error, sent_at, created_at, updated_at
FROM monthly_visitor_report_deliveries
WHERE society_id = $1
  AND report_month = $2
FOR UPDATE
`

type GetMonthlyVisitorReportDeliveryForUpdateParams struct {
	SocietyID   int64       `db:"society_id" json:"society_id"`
	ReportMonth pgtype.Date `db:"report_month" json:"report_month"`
}

func (q *Queries) GetMonthlyVisitorReportDeliveryForUpdate(ctx context.Context, arg GetMonthlyVisitorReportDeliveryForUpdateParams) (MonthlyVisitorReportDelivery, error) {
	row := q.db.QueryRow(ctx, getMonthlyVisitorReportDeliveryForUpdate, arg.SocietyID, arg.ReportMonth)
	var i MonthlyVisitorReportDelivery
	err := row.Scan(
		&i.ID,
		&i.SocietyID,
		&i.ReportMonth,
		&i.Status,
		&i.AttemptCount,
		&i.ProcessingUntil,
		&i.Recipients,
		&i.ProviderMessageID,
		&i.LastError,
		&i.SentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveSocietiesForVisitorReports = `-- name: ListActiveSocietiesForVisitorReports :many
SELECT id, name, email
FROM societies
WHERE status = 'active'
  AND deleted_at IS NULL
ORDER BY id
`

type ListActiveSocietiesForVisitorReportsRow struct {
	ID    int64   `db:"id" json:"id"`
	Name  string  `db:"name" json:"name"`
	Email *string `db:"email" json:"email"`
}

func (q *Queries) ListActiveSocietiesForVisitorReports(ctx context.Context) ([]ListActiveSocietiesForVisitorReportsRow, error) {
	rows, err := q.db.Query(ctx, listActiveSocietiesForVisitorReports)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveSocietiesForVisitorReportsRow{}
	for rows.Next() {
		var i ListActiveSocietiesForVisitorReportsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClaimableMonthlyVisitorReportDeliveries = `-- name: ListClaimableMonthlyVisitorReportDeliveries :many
SELECT d.id, d.society_id, d.report_month, d.status, d.attempt_count, d.processing_until, d.recipients, d.provider_message_id, d.last_error, d.sent_at, d.created_at, d.updated_at, s.name AS society_name, s.email AS society_email
FROM monthly_visitor_report_deliveries d
JOIN societies s ON s.id = d.society_id
WHERE (d.sent_at IS NULL
   OR ($1::boolean AND d.report_month = $2))
  AND (d.processing_until IS NULL OR d.processing_until <= NOW())
  AND s.status = 'active'
  AND s.deleted_at IS NULL
ORDER BY d.report_month, d.society_id
LIMIT $3
`

type ListClaimableMonthlyVisitorReportDeliveriesParams struct {
	AllowResend bool        `db:"allow_resend" json:"allow_resend"`
	ResendMonth pgtype.Date `db:"resend_month" json:"resend_month"`
	BatchSize   int32       `db:"batch_size" json:"batch_size"`
}

type ListClaimableMonthlyVisitorReportDeliveriesRow struct {
	ID                int64              `db:"id" json:"id"`
	SocietyID         int64              `db:"society_id" json:"society_id"`
	ReportMonth       pgtype.Date        `db:"report_month" json:"report_month"`
	Status            string             `db:"status" json:"status"`
	AttemptCount      int32              `db:"attempt_count" json:"attempt_count"`
	ProcessingUntil   pgtype.Timestamptz `db:"processing_until" json:"processing_until"`
	Recipients        []string           `db:"recipients" json:"recipients"`
	ProviderMessageID *string            `db:"provider_message_id" json:"provider_message_id"`
	LastError         *string            `db:"last_error" json:"last_error"`
	SentAt            pgtype.Timestamptz `db:"sent_at" json:"sent_at"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	SocietyName       string             `db:"society_name" json:"society_name"`
	SocietyEmail      *string            `db:"society_email" json:"society_email"`
}

func (q *Queries) ListClaimableMonthlyVisitorReportDeliveries(ctx context.Context, arg ListClaimableMonthlyVisitorReportDeliveriesParams) ([]ListClaimableMonthlyVisitorReportDeliveriesRow, error) {
	rows, err := q.db.Query(ctx, listClaimableMonthlyVisitorReportDeliveries, arg.AllowResend, arg.ResendMonth, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClaimableMonthlyVisitorReportDeliveriesRow{}
	for rows.Next() {
		var i ListClaimableMonthlyVisitorReportDeliveriesRow
		if err := rows.Scan(
			&i.ID,
			&i.SocietyID,
			&i.ReportMonth,
			&i.Status,
			&i.AttemptCount,
			&i.ProcessingUntil,
			&i.Recipients,
			&i.ProviderMessageID,
			&i.LastError,
			&i.SentAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SocietyName,
			&i.SocietyEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFlatMemberInviteCleanupCandidateIDs = `-- name: ListFlatMemberInviteCleanupCandidateIDs :many
SELECT fmi.id
FROM flat_member_invites fmi
WHERE fmi.status IN ('accepted', 'expired', 'cancelled')
  AND fmi.updated_at < $1
ORDER BY fmi.updated_at, fmi.id
LIMIT $2
FOR UPDATE SKIP LOCKED
`

type ListFlatMemberInviteCleanupCandidateIDsParams struct {
	Cutoff    pgtype.Timestamptz `db:"cutoff" json:"cutoff"`
	BatchSize int32              `db:"batch_size" json:"batch_size"`
}

func (q *Queries) ListFlatMemberInviteCleanupCandidateIDs(ctx context.Context, arg ListFlatMemberInviteCleanupCandidateIDsParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, listFlatMemberInviteCleanupCandidateIDs, arg.Cutoff, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMonthlyVisitorReportRecipients = `-- name: ListMonthlyVisitorReportRecipients :many
SELECT DISTINCT LOWER(TRIM(u.email)) AS email
FROM society_members sm
JOIN users u ON u.id = sm.user_id
WHERE sm.society_id = $1
  AND sm.role = 'owner'
  AND sm.status = 'active'
  AND u.is_active = TRUE
  AND u.is_blocked = FALSE
  AND u.deleted_at IS NULL
  AND u.email IS NOT NULL
  AND TRIM(u.email) <> ''
ORDER BY email
`

func (q *Queries) ListMonthlyVisitorReportRecipients(ctx context.Context, societyID int64) ([]string, error) {
	rows, err := q.db.Query(ctx, listMonthlyVisitorReportRecipients, societyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var email string
		if err := rows.Scan(&email); err != nil {
			return nil, err
		}
		items = append(items, email)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMonthlyVisitorReportRows = `-- name: ListMonthlyVisitorReportRows :many
SELECT
    ve.id,
    v.full_name AS visitor_name,
    v.phone_number AS visitor_phone,
    v.email AS visitor_email,
    f.flat_number,
    f.block,
    f.floor,
    ve.source,
    ve.purpose,
    ve.status,
    ve.expected_at,
    ve.expected_checkout_at,
    ve.checked_in_at,
    ve.checked_out_at,
    ve.auto_closed_at,
    ve.vehicle_number,
    ve.vehicle_type,
    ve.companions_count,
    ve.companion_details,
    approver.full_name AS approver_name,
    guard_user.full_name AS guard_name,
    ve.rejection_reason,
    ve.notes,
    ve.created_at,
    ve.updated_at
FROM visitor_entries ve
JOIN visitors v ON v.id = ve.visitor_id
LEFT JOIN flats f
  ON f.id = ve.flat_id
 AND f.society_id = ve.society_id
LEFT JOIN users approver ON approver.id = ve.approved_by
LEFT JOIN users guard_user ON guard_user.id = ve.handled_by_guard_id
WHERE ve.society_id = $1
  AND ve.created_at >= $2
  AND ve.created_at < $3
ORDER BY ve.created_at, ve.id
`

type ListMonthlyVisitorReportRowsParams struct {
	SocietyID   int64              `db:"society_id" json:"society_id"`
	PeriodStart pgtype.Timestamptz `db:"period_start" json:"period_start"`
	PeriodEnd   pgtype.Timestamptz `db:"period_end" json:"period_end"`
}

type ListMonthlyVisitorReportRowsRow struct {
	ID                 int64               `db:"id" json:"id"`
	VisitorName        string              `db:"visitor_name" json:"visitor_name"`
	VisitorPhone       *string             `db:"visitor_phone" json:"visitor_phone"`
	VisitorEmail       *string             `db:"visitor_email" json:"visitor_email"`
	FlatNumber         *string             `db:"flat_number" json:"flat_number"`
	Block              *string             `db:"block" json:"block"`
	Floor              *string             `db:"floor" json:"floor"`
	Source             VisitorSource       `db:"source" json:"source"`
	Purpose            VisitorPurpose      `db:"purpose" json:"purpose"`
	Status             VisitorStatus       `db:"status" json:"status"`
	ExpectedAt         pgtype.Timestamptz  `db:"expected_at" json:"expected_at"`
	ExpectedCheckoutAt pgtype.Timestamptz  `db:"expected_checkout_at" json:"expected_checkout_at"`
	CheckedInAt        pgtype.Timestamptz  `db:"checked_in_at" json:"checked_in_at"`
	CheckedOutAt       pgtype.Timestamptz  `db:"checked_out_at" json:"checked_out_at"`
	AutoClosedAt       pgtype.Timestamptz  `db:"auto_closed_at" json:"auto_closed_at"`
	VehicleNumber      *string             `db:"vehicle_number" json:"vehicle_number"`
	VehicleType        *VisitorVehicleType `db:"vehicle_type" json:"vehicle_type"`
	CompanionsCount    int32               `db:"companions_count" json:"companions_count"`
	CompanionDetails   []byte              `db:"companion_details" json:"companion_details"`
	ApproverName       *string             `db:"approver_name" json:"approver_name"`
	GuardName          *string             `db:"guard_name" json:"guard_name"`
	RejectionReason    *string             `db:"rejection_reason" json:"rejection_reason"`
	Notes              *string             `db:"notes" json:"notes"`
	CreatedAt          pgtype.Timestamptz  `db:"created_at" json:"created_at"`
	UpdatedAt          pgtype.Timestamptz  `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ListMonthlyVisitorReportRows(ctx context.Context, arg ListMonthlyVisitorReportRowsParams) ([]ListMonthlyVisitorReportRowsRow, error) {
	rows, err := q.db.Query(ctx, listMonthlyVisitorReportRows, arg.SocietyID, arg.PeriodStart, arg.PeriodEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMonthlyVisitorReportRowsRow{}
	for rows.Next() {
		var i ListMonthlyVisitorReportRowsRow
		if err := rows.Scan(
			&i.ID,
			&i.VisitorName,
			&i.VisitorPhone,
			&i.VisitorEmail,
			&i.FlatNumber,
			&i.Block,
			&i.Floor,
			&i.Source,
			&i.Purpose,
			&i.Status,
			&i.ExpectedAt,
			&i.ExpectedCheckoutAt,
			&i.CheckedInAt,
			&i.CheckedOutAt,
			&i.AutoClosedAt,
			&i.VehicleNumber,
			&i.VehicleType,
			&i.CompanionsCount,
			&i.CompanionDetails,
			&i.ApproverName,
			&i.GuardName,
			&i.RejectionReason,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVisitorEntryCleanupWindows = `-- name: ListVisitorEntryCleanupWindows :many
SELECT DISTINCT d.society_id, d.report_month
FROM monthly_visitor_report_deliveries d
JOIN visitor_entries ve
  ON ve.society_id = d.society_id
 AND ve.created_at >= (d.report_month::timestamp AT TIME ZONE $1::text)
 AND ve.created_at < ((d.report_month + INTERVAL '1 month')::timestamp AT TIME ZONE $1::text)
WHERE d.sent_at IS NOT NULL
  AND ve.status IN ('rejected', 'checked_out', 'cancelled', 'expired', 'auto_closed')
  AND ve.updated_at < $2
ORDER BY d.report_month, d.society_id
`

type ListVisitorEntryCleanupWindowsParams struct {
	JobTimezone string             `db:"job_timezone" json:"job_timezone"`
	Cutoff      pgtype.Timestamptz `db:"cutoff" json:"cutoff"`
}

type ListVisitorEntryCleanupWindowsRow struct {
	SocietyID   int64       `db:"society_id" json:"society_id"`
	ReportMonth pgtype.Date `db:"report_month" json:"report_month"`
}

func (q *Queries) ListVisitorEntryCleanupWindows(ctx context.Context, arg ListVisitorEntryCleanupWindowsParams) ([]ListVisitorEntryCleanupWindowsRow, error) {
	rows, err := q.db.Query(ctx, listVisitorEntryCleanupWindows, arg.JobTimezone, arg.Cutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVisitorEntryCleanupWindowsRow{}
	for rows.Next() {
		var i ListVisitorEntryCleanupWindowsRow
		if err := rows.Scan(&i.SocietyID, &i.ReportMonth); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVisitorImageDeletions = `-- name: ListVisitorImageDeletions :many
SELECT id, file_id FROM visitor_image_deletions
WHERE id > $1
ORDER BY id LIMIT $2
`

type ListVisitorImageDeletionsParams struct {
	AfterID   int64 `db:"after_id" json:"after_id"`
	BatchSize int32 `db:"batch_size" json:"batch_size"`
}

type ListVisitorImageDeletionsRow struct {
	ID     int64  `db:"id" json:"id"`
	FileID string `db:"file_id" json:"file_id"`
}

func (q *Queries) ListVisitorImageDeletions(ctx context.Context, arg ListVisitorImageDeletionsParams) ([]ListVisitorImageDeletionsRow, error) {
	rows, err := q.db.Query(ctx, listVisitorImageDeletions, arg.AfterID, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVisitorImageDeletionsRow{}
	for rows.Next() {
		var i ListVisitorImageDeletionsRow
		if err := rows.Scan(&i.ID, &i.FileID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVisitorInviteCleanupCandidateIDs = `-- name: ListVisitorInviteCleanupCandidateIDs :many
SELECT vi.id
FROM visitor_invites vi
WHERE vi.status IN ('used', 'expired', 'cancelled')
  AND vi.updated_at < $1
  AND NOT EXISTS (
      SELECT 1 FROM visitor_entries ve WHERE ve.invite_id = vi.id
  )
ORDER BY vi.updated_at, vi.id
LIMIT $2
FOR UPDATE SKIP LOCKED
`

type ListVisitorInviteCleanupCandidateIDsParams struct {
	Cutoff    pgtype.Timestamptz `db:"cutoff" json:"cutoff"`
	BatchSize int32              `db:"batch_size" json:"batch_size"`
}

func (q *Queries) ListVisitorInviteCleanupCandidateIDs(ctx context.Context, arg ListVisitorInviteCleanupCandidateIDsParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, listVisitorInviteCleanupCandidateIDs, arg.Cutoff, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCleanupVisitors = `-- name: LockCleanupVisitors :many
SELECT id FROM visitors
WHERE id = ANY($1::bigint[])
ORDER BY id FOR UPDATE
`

func (q *Queries) LockCleanupVisitors(ctx context.Context, ids []int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, lockCleanupVisitors, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockOldOrphanVisitors = `-- name: LockOldOrphanVisitors :many
SELECT v.id FROM visitors v
WHERE v.updated_at < $1
  AND NOT EXISTS (SELECT 1 FROM visitor_entries ve WHERE ve.visitor_id = v.id)
ORDER BY v.id LIMIT $2
FOR UPDATE OF v SKIP LOCKED
`

type LockOldOrphanVisitorsParams struct {
	Cutoff    pgtype.Timestamptz `db:"cutoff" json:"cutoff"`
	BatchSize int32              `db:"batch_size" json:"batch_size"`
}

func (q *Queries) LockOldOrphanVisitors(ctx context.Context, arg LockOldOrphanVisitorsParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, lockOldOrphanVisitors, arg.Cutoff, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queueVisitorImageDeletion = `-- name: QueueVisitorImageDeletion :exec
INSERT INTO visitor_image_deletions (file_id) VALUES ($1)
ON CONFLICT (file_id) DO NOTHING
`

func (q *Queries) QueueVisitorImageDeletion(ctx context.Context, fileID string) error {
	_, err := q.db.Exec(ctx, queueVisitorImageDeletion, fileID)
	return err
}
