// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: maintenance.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const auditMaintenanceReconciliation = `-- name: AuditMaintenanceReconciliation :exec
INSERT INTO maintenance_billing_audit(society_id,actor_id,event_type,entity_id,details)
VALUES($1,$2,'billing_reconciled',$3,$4)
`

type AuditMaintenanceReconciliationParams struct {
	SocietyID int64  `db:"society_id" json:"society_id"`
	ActorID   *int64 `db:"actor_id" json:"actor_id"`
	EntityID  int64  `db:"entity_id" json:"entity_id"`
	Details   []byte `db:"details" json:"details"`
}

func (q *Queries) AuditMaintenanceReconciliation(ctx context.Context, arg AuditMaintenanceReconciliationParams) error {
	_, err := q.db.Exec(ctx, auditMaintenanceReconciliation,
		arg.SocietyID,
		arg.ActorID,
		arg.EntityID,
		arg.Details,
	)
	return err
}

const claimMaintenanceDelivery = `-- name: ClaimMaintenanceDelivery :one
UPDATE maintenance_notification_deliveries d SET attempts=d.attempts+1, available_at=now()+interval '5 minutes', lease_token=$1
WHERE d.id=(SELECT id FROM maintenance_notification_deliveries WHERE completed_at IS NULL AND available_at<=now() ORDER BY available_at,id FOR UPDATE SKIP LOCKED LIMIT 1)
RETURNING d.id, d.bill_id, d.user_id, d.attempts, d.available_at, d.lease_token, d.completed_at, d.last_error, d.event_type, d.event_key, d.audience, d.event_data
`

func (q *Queries) ClaimMaintenanceDelivery(ctx context.Context, leaseToken pgtype.UUID) (MaintenanceNotificationDelivery, error) {
	row := q.db.QueryRow(ctx, claimMaintenanceDelivery, leaseToken)
	var i MaintenanceNotificationDelivery
	err := row.Scan(
		&i.ID,
		&i.BillID,
		&i.UserID,
		&i.Attempts,
		&i.AvailableAt,
		&i.LeaseToken,
		&i.CompletedAt,
		&i.LastError,
		&i.EventType,
		&i.EventKey,
		&i.Audience,
		&i.EventData,
	)
	return i, err
}

const completeMaintenanceDelivery = `-- name: CompleteMaintenanceDelivery :exec
UPDATE maintenance_notification_deliveries SET completed_at=now(),last_error=NULL WHERE id=$1 AND lease_token=$2
`

type CompleteMaintenanceDeliveryParams struct {
	ID         int64       `db:"id" json:"id"`
	LeaseToken pgtype.UUID `db:"lease_token" json:"lease_token"`
}

func (q *Queries) CompleteMaintenanceDelivery(ctx context.Context, arg CompleteMaintenanceDeliveryParams) error {
	_, err := q.db.Exec(ctx, completeMaintenanceDelivery, arg.ID, arg.LeaseToken)
	return err
}

const countMaintenanceBills = `-- name: CountMaintenanceBills :one
SELECT count(*)::bigint FROM maintenance_bills b
JOIN maintenance_bill_balances v ON v.bill_id=b.id
JOIN flats bf ON bf.id=b.flat_id AND bf.society_id=b.society_id AND bf.is_active
WHERE b.society_id=$1
AND ($2::bigint=0 OR b.id=$2)
AND ($3::bigint=0 OR b.flat_id=$3)
AND ($4::bigint=0 OR b.id<$4)
AND ($5::date IS NULL OR b.billing_month=$5)
AND ($6::text='' OR v.payment_status=$6)
AND ($7::text=''
 OR ($7='outstanding' AND v.outstanding_amount_paise>0)
 OR $7=CASE WHEN v.payment_status='paid' THEN 'paid' WHEN v.payment_claim_status='pending' THEN 'pending_review' WHEN v.payment_claim_status='rejected' THEN 'rejected' ELSE v.payment_status END)
AND ($8::text='' OR b.bill_number=$8)
AND ($9::text IS NULL OR COALESCE(bf.block, '') ILIKE '%' || $9::text || '%')
AND ($10::text IS NULL OR bf.flat_number ILIKE '%' || $10::text || '%')
AND (
    $11::text = ''
    OR bf.flat_number ILIKE '%' || $11::text || '%'
    OR COALESCE(bf.block, '') ILIKE '%' || $11::text || '%'
)
AND (NOT $12::boolean OR EXISTS (
 SELECT 1 FROM flat_residents r JOIN society_members m ON m.society_id=r.society_id AND m.user_id=r.user_id
 JOIN flats f ON f.id=r.flat_id AND f.society_id=r.society_id AND f.is_active
 WHERE r.society_id=b.society_id AND r.flat_id=b.flat_id AND r.user_id=$13 AND r.status='active' AND m.status='active'
))
`

type CountMaintenanceBillsParams struct {
	SocietyID     int64       `db:"society_id" json:"society_id"`
	BillID        int64       `db:"bill_id" json:"bill_id"`
	FlatID        int64       `db:"flat_id" json:"flat_id"`
	BeforeID      int64       `db:"before_id" json:"before_id"`
	Month         pgtype.Date `db:"month" json:"month"`
	Status        string      `db:"status" json:"status"`
	DisplayStatus string      `db:"display_status" json:"display_status"`
	BillNumber    string      `db:"bill_number" json:"bill_number"`
	Block         *string     `db:"block" json:"block"`
	FlatNumber    *string     `db:"flat_number" json:"flat_number"`
	Search        string      `db:"search" json:"search"`
	Resident      bool        `db:"resident" json:"resident"`
	UserID        int64       `db:"user_id" json:"user_id"`
}

func (q *Queries) CountMaintenanceBills(ctx context.Context, arg CountMaintenanceBillsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMaintenanceBills,
		arg.SocietyID,
		arg.BillID,
		arg.FlatID,
		arg.BeforeID,
		arg.Month,
		arg.Status,
		arg.DisplayStatus,
		arg.BillNumber,
		arg.Block,
		arg.FlatNumber,
		arg.Search,
		arg.Resident,
		arg.UserID,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createMaintenanceBill = `-- name: CreateMaintenanceBill :one
INSERT INTO maintenance_bills(run_id,society_id,flat_id,billing_month,bill_number,due_date,timezone,total_paise,snapshot,billed_party)
VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING id
`

type CreateMaintenanceBillParams struct {
	RunID        int64       `db:"run_id" json:"run_id"`
	SocietyID    int64       `db:"society_id" json:"society_id"`
	FlatID       int64       `db:"flat_id" json:"flat_id"`
	BillingMonth pgtype.Date `db:"billing_month" json:"billing_month"`
	BillNumber   string      `db:"bill_number" json:"bill_number"`
	DueDate      pgtype.Date `db:"due_date" json:"due_date"`
	Timezone     string      `db:"timezone" json:"timezone"`
	TotalPaise   int64       `db:"total_paise" json:"total_paise"`
	Snapshot     []byte      `db:"snapshot" json:"snapshot"`
	BilledParty  []byte      `db:"billed_party" json:"billed_party"`
}

func (q *Queries) CreateMaintenanceBill(ctx context.Context, arg CreateMaintenanceBillParams) (int64, error) {
	row := q.db.QueryRow(ctx, createMaintenanceBill,
		arg.RunID,
		arg.SocietyID,
		arg.FlatID,
		arg.BillingMonth,
		arg.BillNumber,
		arg.DueDate,
		arg.Timezone,
		arg.TotalPaise,
		arg.Snapshot,
		arg.BilledParty,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createMaintenanceBillItem = `-- name: CreateMaintenanceBillItem :exec
INSERT INTO maintenance_bill_items(bill_id,position,description,amount_paise) VALUES($1,$2,$3,$4)
`

type CreateMaintenanceBillItemParams struct {
	BillID      int64  `db:"bill_id" json:"bill_id"`
	Position    int32  `db:"position" json:"position"`
	Description string `db:"description" json:"description"`
	AmountPaise int64  `db:"amount_paise" json:"amount_paise"`
}

func (q *Queries) CreateMaintenanceBillItem(ctx context.Context, arg CreateMaintenanceBillItemParams) error {
	_, err := q.db.Exec(ctx, createMaintenanceBillItem,
		arg.BillID,
		arg.Position,
		arg.Description,
		arg.AmountPaise,
	)
	return err
}

const createMaintenanceRun = `-- name: CreateMaintenanceRun :one
INSERT INTO maintenance_billing_runs(society_id,billing_month,snapshot,created_by) VALUES($1,$2,$3,$4) RETURNING id
`

type CreateMaintenanceRunParams struct {
	SocietyID    int64       `db:"society_id" json:"society_id"`
	BillingMonth pgtype.Date `db:"billing_month" json:"billing_month"`
	Snapshot     []byte      `db:"snapshot" json:"snapshot"`
	CreatedBy    *int64      `db:"created_by" json:"created_by"`
}

func (q *Queries) CreateMaintenanceRun(ctx context.Context, arg CreateMaintenanceRunParams) (int64, error) {
	row := q.db.QueryRow(ctx, createMaintenanceRun,
		arg.SocietyID,
		arg.BillingMonth,
		arg.Snapshot,
		arg.CreatedBy,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteMaintenanceTypeRates = `-- name: DeleteMaintenanceTypeRates :exec
DELETE FROM maintenance_type_rates WHERE society_id=$1
`

func (q *Queries) DeleteMaintenanceTypeRates(ctx context.Context, societyID int64) error {
	_, err := q.db.Exec(ctx, deleteMaintenanceTypeRates, societyID)
	return err
}

const enqueueMaintenanceNotifications = `-- name: EnqueueMaintenanceNotifications :exec
INSERT INTO maintenance_notification_deliveries(bill_id,user_id,event_key)
SELECT b.id,r.user_id,'maintenance_bill_generated:'||b.id FROM maintenance_bills b JOIN flat_residents r ON r.society_id=b.society_id AND r.flat_id=b.flat_id
JOIN society_members m ON m.society_id=r.society_id AND m.user_id=r.user_id AND m.status='active'
WHERE b.id=$1 AND r.status='active'
ON CONFLICT(user_id,event_key) DO NOTHING
`

func (q *Queries) EnqueueMaintenanceNotifications(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, enqueueMaintenanceNotifications, id)
	return err
}

const getMaintenanceDeliveryBill = `-- name: GetMaintenanceDeliveryBill :one
SELECT b.id, b.run_id, b.society_id, b.flat_id, b.billing_month, b.bill_number, b.due_date, b.timezone, b.total_paise, b.snapshot, b.billed_party, b.created_at, b.issuer_snapshot FROM maintenance_bills b JOIN societies s ON s.id=b.society_id
WHERE b.id=$1 AND s.status='active' AND s.deleted_at IS NULL AND (
($2::text='admin' AND EXISTS(SELECT 1 FROM society_members m WHERE m.society_id=b.society_id AND m.user_id=$3 AND m.status='active' AND m.role IN ('owner','admin')))
OR ($2::text='resident' AND EXISTS(
 SELECT 1 FROM flat_residents r JOIN society_members m ON m.society_id=r.society_id AND m.user_id=r.user_id
 JOIN flats f ON f.id=r.flat_id AND f.society_id=r.society_id AND f.is_active
 WHERE r.society_id=b.society_id AND r.flat_id=b.flat_id AND r.user_id=$3 AND r.status='active' AND m.status='active'
)))
`

type GetMaintenanceDeliveryBillParams struct {
	BillID   int64  `db:"bill_id" json:"bill_id"`
	Audience string `db:"audience" json:"audience"`
	UserID   int64  `db:"user_id" json:"user_id"`
}

func (q *Queries) GetMaintenanceDeliveryBill(ctx context.Context, arg GetMaintenanceDeliveryBillParams) (MaintenanceBill, error) {
	row := q.db.QueryRow(ctx, getMaintenanceDeliveryBill, arg.BillID, arg.Audience, arg.UserID)
	var i MaintenanceBill
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.SocietyID,
		&i.FlatID,
		&i.BillingMonth,
		&i.BillNumber,
		&i.DueDate,
		&i.Timezone,
		&i.TotalPaise,
		&i.Snapshot,
		&i.BilledParty,
		&i.CreatedAt,
		&i.IssuerSnapshot,
	)
	return i, err
}

const getMaintenanceRun = `-- name: GetMaintenanceRun :one
SELECT r.id, r.snapshot, (SELECT count(*) FROM maintenance_bills b WHERE b.run_id=r.id)::bigint AS bill_count FROM maintenance_billing_runs r WHERE r.society_id=$1 AND r.billing_month=$2
`

type GetMaintenanceRunParams struct {
	SocietyID    int64       `db:"society_id" json:"society_id"`
	BillingMonth pgtype.Date `db:"billing_month" json:"billing_month"`
}

type GetMaintenanceRunRow struct {
	ID        int64  `db:"id" json:"id"`
	Snapshot  []byte `db:"snapshot" json:"snapshot"`
	BillCount int64  `db:"bill_count" json:"bill_count"`
}

func (q *Queries) GetMaintenanceRun(ctx context.Context, arg GetMaintenanceRunParams) (GetMaintenanceRunRow, error) {
	row := q.db.QueryRow(ctx, getMaintenanceRun, arg.SocietyID, arg.BillingMonth)
	var i GetMaintenanceRunRow
	err := row.Scan(&i.ID, &i.Snapshot, &i.BillCount)
	return i, err
}

const getMaintenanceSettings = `-- name: GetMaintenanceSettings :one
SELECT config FROM maintenance_settings WHERE society_id=$1
`

func (q *Queries) GetMaintenanceSettings(ctx context.Context, societyID int64) ([]byte, error) {
	row := q.db.QueryRow(ctx, getMaintenanceSettings, societyID)
	var config []byte
	err := row.Scan(&config)
	return config, err
}

const listMaintenanceBills = `-- name: ListMaintenanceBills :many
SELECT b.id, b.run_id, b.society_id, b.flat_id, b.billing_month, b.bill_number, b.due_date, b.timezone, b.total_paise, b.snapshot, b.billed_party, b.created_at, b.issuer_snapshot, v.paid_amount_paise,v.outstanding_amount_paise,v.payment_claim_status,v.payment_status, p.credit_date AS paid_on FROM maintenance_bills b
JOIN maintenance_bill_balances v ON v.bill_id=b.id
LEFT JOIN maintenance_payments p ON p.bill_id=b.id AND p.society_id=b.society_id AND p.status='verified'
JOIN flats bf ON bf.id=b.flat_id AND bf.society_id=b.society_id AND bf.is_active
WHERE b.society_id=$1
AND ($2::bigint=0 OR b.id=$2)
AND ($3::bigint=0 OR b.flat_id=$3)
AND ($4::bigint=0 OR b.id<$4)
AND ($5::date IS NULL OR b.billing_month=$5)
AND ($6::text='' OR v.payment_status=$6)
AND ($7::text=''
 OR ($7='outstanding' AND v.outstanding_amount_paise>0)
 OR $7=CASE WHEN v.payment_status='paid' THEN 'paid' WHEN v.payment_claim_status='pending' THEN 'pending_review' WHEN v.payment_claim_status='rejected' THEN 'rejected' ELSE v.payment_status END)
AND ($8::text='' OR b.bill_number=$8)
AND ($9::text IS NULL OR COALESCE(bf.block, '') ILIKE '%' || $9::text || '%')
AND ($10::text IS NULL OR bf.flat_number ILIKE '%' || $10::text || '%')
AND (
    $11::text = ''
    OR bf.flat_number ILIKE '%' || $11::text || '%'
    OR COALESCE(bf.block, '') ILIKE '%' || $11::text || '%'
)
AND (NOT $12::boolean OR EXISTS (
 SELECT 1 FROM flat_residents r JOIN society_members m ON m.society_id=r.society_id AND m.user_id=r.user_id
 JOIN flats f ON f.id=r.flat_id AND f.society_id=r.society_id AND f.is_active
 WHERE r.society_id=b.society_id AND r.flat_id=b.flat_id AND r.user_id=$13 AND r.status='active' AND m.status='active'
))
ORDER BY b.id DESC LIMIT $15 OFFSET $14
`

type ListMaintenanceBillsParams struct {
	SocietyID     int64       `db:"society_id" json:"society_id"`
	BillID        int64       `db:"bill_id" json:"bill_id"`
	FlatID        int64       `db:"flat_id" json:"flat_id"`
	BeforeID      int64       `db:"before_id" json:"before_id"`
	Month         pgtype.Date `db:"month" json:"month"`
	Status        string      `db:"status" json:"status"`
	DisplayStatus string      `db:"display_status" json:"display_status"`
	BillNumber    string      `db:"bill_number" json:"bill_number"`
	Block         *string     `db:"block" json:"block"`
	FlatNumber    *string     `db:"flat_number" json:"flat_number"`
	Search        string      `db:"search" json:"search"`
	Resident      bool        `db:"resident" json:"resident"`
	UserID        int64       `db:"user_id" json:"user_id"`
	PageOffset    int32       `db:"page_offset" json:"page_offset"`
	Limit         int32       `db:"limit" json:"limit"`
}

type ListMaintenanceBillsRow struct {
	MaintenanceBill        MaintenanceBill `db:"maintenance_bill" json:"maintenance_bill"`
	PaidAmountPaise        int64           `db:"paid_amount_paise" json:"paid_amount_paise"`
	OutstandingAmountPaise int64           `db:"outstanding_amount_paise" json:"outstanding_amount_paise"`
	PaymentClaimStatus     string          `db:"payment_claim_status" json:"payment_claim_status"`
	PaymentStatus          string          `db:"payment_status" json:"payment_status"`
	PaidOn                 pgtype.Date     `db:"paid_on" json:"paid_on"`
}

func (q *Queries) ListMaintenanceBills(ctx context.Context, arg ListMaintenanceBillsParams) ([]ListMaintenanceBillsRow, error) {
	rows, err := q.db.Query(ctx, listMaintenanceBills,
		arg.SocietyID,
		arg.BillID,
		arg.FlatID,
		arg.BeforeID,
		arg.Month,
		arg.Status,
		arg.DisplayStatus,
		arg.BillNumber,
		arg.Block,
		arg.FlatNumber,
		arg.Search,
		arg.Resident,
		arg.UserID,
		arg.PageOffset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMaintenanceBillsRow{}
	for rows.Next() {
		var i ListMaintenanceBillsRow
		if err := rows.Scan(
			&i.MaintenanceBill.ID,
			&i.MaintenanceBill.RunID,
			&i.MaintenanceBill.SocietyID,
			&i.MaintenanceBill.FlatID,
			&i.MaintenanceBill.BillingMonth,
			&i.MaintenanceBill.BillNumber,
			&i.MaintenanceBill.DueDate,
			&i.MaintenanceBill.Timezone,
			&i.MaintenanceBill.TotalPaise,
			&i.MaintenanceBill.Snapshot,
			&i.MaintenanceBill.BilledParty,
			&i.MaintenanceBill.CreatedAt,
			&i.MaintenanceBill.IssuerSnapshot,
			&i.PaidAmountPaise,
			&i.OutstandingAmountPaise,
			&i.PaymentClaimStatus,
			&i.PaymentStatus,
			&i.PaidOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaintenanceFlats = `-- name: ListMaintenanceFlats :many
SELECT f.id, f.flat_number, f.block, f.flat_type, f.area_sqft_hundredths,
 COALESCE((SELECT jsonb_build_object('user_id',u.id::text,'name',u.full_name) FROM flat_residents r JOIN users u ON u.id=r.user_id WHERE r.society_id=f.society_id AND r.flat_id=f.id AND r.status='active' AND r.is_primary ORDER BY r.id LIMIT 1), '{}'::jsonb)::jsonb AS billed_party
FROM flats f WHERE f.society_id=$1 AND f.is_active AND f.status::text=ANY($2::text[]) ORDER BY f.id
`

type ListMaintenanceFlatsParams struct {
	SocietyID int64    `db:"society_id" json:"society_id"`
	Statuses  []string `db:"statuses" json:"statuses"`
}

type ListMaintenanceFlatsRow struct {
	ID                 int64   `db:"id" json:"id"`
	FlatNumber         string  `db:"flat_number" json:"flat_number"`
	Block              *string `db:"block" json:"block"`
	FlatType           *string `db:"flat_type" json:"flat_type"`
	AreaSqftHundredths *int64  `db:"area_sqft_hundredths" json:"area_sqft_hundredths"`
	BilledParty        []byte  `db:"billed_party" json:"billed_party"`
}

func (q *Queries) ListMaintenanceFlats(ctx context.Context, arg ListMaintenanceFlatsParams) ([]ListMaintenanceFlatsRow, error) {
	rows, err := q.db.Query(ctx, listMaintenanceFlats, arg.SocietyID, arg.Statuses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMaintenanceFlatsRow{}
	for rows.Next() {
		var i ListMaintenanceFlatsRow
		if err := rows.Scan(
			&i.ID,
			&i.FlatNumber,
			&i.Block,
			&i.FlatType,
			&i.AreaSqftHundredths,
			&i.BilledParty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaintenanceIssuedFlats = `-- name: ListMaintenanceIssuedFlats :many
SELECT flat_id FROM maintenance_bills WHERE society_id=$1 AND billing_month=$2 ORDER BY flat_id
`

type ListMaintenanceIssuedFlatsParams struct {
	SocietyID    int64       `db:"society_id" json:"society_id"`
	BillingMonth pgtype.Date `db:"billing_month" json:"billing_month"`
}

func (q *Queries) ListMaintenanceIssuedFlats(ctx context.Context, arg ListMaintenanceIssuedFlatsParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, listMaintenanceIssuedFlats, arg.SocietyID, arg.BillingMonth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var flat_id int64
		if err := rows.Scan(&flat_id); err != nil {
			return nil, err
		}
		items = append(items, flat_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaintenanceSocieties = `-- name: ListMaintenanceSocieties :many
SELECT m.society_id FROM maintenance_settings m JOIN societies s ON s.id=m.society_id WHERE m.enabled AND s.status='active' AND s.deleted_at IS NULL ORDER BY m.society_id
`

func (q *Queries) ListMaintenanceSocieties(ctx context.Context) ([]int64, error) {
	rows, err := q.db.Query(ctx, listMaintenanceSocieties)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var society_id int64
		if err := rows.Scan(&society_id); err != nil {
			return nil, err
		}
		items = append(items, society_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maintenanceAdmin = `-- name: MaintenanceAdmin :one
SELECT EXISTS(SELECT 1 FROM society_members m JOIN societies s ON s.id=m.society_id WHERE m.society_id=$1 AND m.user_id=$2 AND m.status='active' AND m.role IN ('owner','admin') AND s.status='active' AND s.deleted_at IS NULL)::boolean
`

type MaintenanceAdminParams struct {
	SocietyID int64 `db:"society_id" json:"society_id"`
	UserID    int64 `db:"user_id" json:"user_id"`
}

func (q *Queries) MaintenanceAdmin(ctx context.Context, arg MaintenanceAdminParams) (bool, error) {
	row := q.db.QueryRow(ctx, maintenanceAdmin, arg.SocietyID, arg.UserID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const maintenanceLock = `-- name: MaintenanceLock :exec
SELECT pg_advisory_xact_lock(hashtextextended('maintenance/' || $1::bigint::text, 0))
`

func (q *Queries) MaintenanceLock(ctx context.Context, societyID int64) error {
	_, err := q.db.Exec(ctx, maintenanceLock, societyID)
	return err
}

const retryMaintenanceDelivery = `-- name: RetryMaintenanceDelivery :exec
UPDATE maintenance_notification_deliveries SET available_at=now()+(LEAST(3600,30*power(2,LEAST(attempts,7)))::int * interval '1 second'), last_error=$1 WHERE id=$2 AND lease_token=$3
`

type RetryMaintenanceDeliveryParams struct {
	LastError  *string     `db:"last_error" json:"last_error"`
	ID         int64       `db:"id" json:"id"`
	LeaseToken pgtype.UUID `db:"lease_token" json:"lease_token"`
}

func (q *Queries) RetryMaintenanceDelivery(ctx context.Context, arg RetryMaintenanceDeliveryParams) error {
	_, err := q.db.Exec(ctx, retryMaintenanceDelivery, arg.LastError, arg.ID, arg.LeaseToken)
	return err
}

const saveMaintenanceSettings = `-- name: SaveMaintenanceSettings :exec
INSERT INTO maintenance_settings(society_id, enabled, config, updated_by) VALUES($1,$2,$3,$4)
ON CONFLICT(society_id) DO UPDATE SET enabled=excluded.enabled, config=excluded.config, updated_by=excluded.updated_by, updated_at=now()
`

type SaveMaintenanceSettingsParams struct {
	SocietyID int64  `db:"society_id" json:"society_id"`
	Enabled   bool   `db:"enabled" json:"enabled"`
	Config    []byte `db:"config" json:"config"`
	UpdatedBy *int64 `db:"updated_by" json:"updated_by"`
}

func (q *Queries) SaveMaintenanceSettings(ctx context.Context, arg SaveMaintenanceSettingsParams) error {
	_, err := q.db.Exec(ctx, saveMaintenanceSettings,
		arg.SocietyID,
		arg.Enabled,
		arg.Config,
		arg.UpdatedBy,
	)
	return err
}

const saveMaintenanceTypeRate = `-- name: SaveMaintenanceTypeRate :exec
INSERT INTO maintenance_type_rates(society_id,flat_type,amount_paise) VALUES($1,$2,$3)
`

type SaveMaintenanceTypeRateParams struct {
	SocietyID   int64  `db:"society_id" json:"society_id"`
	FlatType    string `db:"flat_type" json:"flat_type"`
	AmountPaise int64  `db:"amount_paise" json:"amount_paise"`
}

func (q *Queries) SaveMaintenanceTypeRate(ctx context.Context, arg SaveMaintenanceTypeRateParams) error {
	_, err := q.db.Exec(ctx, saveMaintenanceTypeRate, arg.SocietyID, arg.FlatType, arg.AmountPaise)
	return err
}
