// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: maintenance_reminders.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const enqueueMaintenanceReminder = `-- name: EnqueueMaintenanceReminder :execrows
INSERT INTO maintenance_notification_deliveries(bill_id,user_id,event_type,event_key,audience,event_data)
SELECT b.id,r.user_id,'maintenance_payment_reminder',$1,'resident',$2::jsonb
FROM maintenance_bills b
JOIN maintenance_bill_balances v ON v.bill_id=b.id AND v.outstanding_amount_paise>0 AND v.payment_claim_status IS DISTINCT FROM 'pending'
JOIN maintenance_settings ms ON ms.society_id=b.society_id AND ms.enabled
JOIN societies s ON s.id=b.society_id AND s.status='active' AND s.deleted_at IS NULL
JOIN flats f ON f.id=b.flat_id AND f.society_id=b.society_id AND f.is_active
JOIN flat_residents r ON r.flat_id=f.id AND r.society_id=f.society_id AND r.status='active'
JOIN society_members m ON m.society_id=r.society_id AND m.user_id=r.user_id AND m.status='active' AND m.role<>'staff'
WHERE b.id=$3 AND b.society_id=$4
ON CONFLICT(user_id,event_key) DO NOTHING
`

type EnqueueMaintenanceReminderParams struct {
	EventKey  string `db:"event_key" json:"event_key"`
	EventData []byte `db:"event_data" json:"event_data"`
	BillID    int64  `db:"bill_id" json:"bill_id"`
	SocietyID int64  `db:"society_id" json:"society_id"`
}

func (q *Queries) EnqueueMaintenanceReminder(ctx context.Context, arg EnqueueMaintenanceReminderParams) (int64, error) {
	result, err := q.db.Exec(ctx, enqueueMaintenanceReminder,
		arg.EventKey,
		arg.EventData,
		arg.BillID,
		arg.SocietyID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getMaintenanceReminderDelivery = `-- name: GetMaintenanceReminderDelivery :one
SELECT b.bill_number, b.billing_month, b.due_date, v.outstanding_amount_paise
FROM maintenance_notification_deliveries d
JOIN maintenance_bills b ON b.id=d.bill_id
JOIN maintenance_bill_balances v ON v.bill_id=b.id AND v.outstanding_amount_paise>0 AND v.payment_claim_status IS DISTINCT FROM 'pending'
JOIN maintenance_settings ms ON ms.society_id=b.society_id AND ms.enabled
WHERE d.user_id=$1 AND d.event_key=$2
AND d.event_type='maintenance_payment_reminder' AND b.society_id=$3
`

type GetMaintenanceReminderDeliveryParams struct {
	UserID    int64  `db:"user_id" json:"user_id"`
	EventKey  string `db:"event_key" json:"event_key"`
	SocietyID int64  `db:"society_id" json:"society_id"`
}

type GetMaintenanceReminderDeliveryRow struct {
	BillNumber             string      `db:"bill_number" json:"bill_number"`
	BillingMonth           pgtype.Date `db:"billing_month" json:"billing_month"`
	DueDate                pgtype.Date `db:"due_date" json:"due_date"`
	OutstandingAmountPaise int64       `db:"outstanding_amount_paise" json:"outstanding_amount_paise"`
}

func (q *Queries) GetMaintenanceReminderDelivery(ctx context.Context, arg GetMaintenanceReminderDeliveryParams) (GetMaintenanceReminderDeliveryRow, error) {
	row := q.db.QueryRow(ctx, getMaintenanceReminderDelivery, arg.UserID, arg.EventKey, arg.SocietyID)
	var i GetMaintenanceReminderDeliveryRow
	err := row.Scan(
		&i.BillNumber,
		&i.BillingMonth,
		&i.DueDate,
		&i.OutstandingAmountPaise,
	)
	return i, err
}

const listMaintenanceReminderCandidates = `-- name: ListMaintenanceReminderCandidates :many
SELECT b.id, b.due_date, b.timezone
FROM maintenance_bills b
JOIN maintenance_bill_balances v ON v.bill_id=b.id
JOIN maintenance_settings ms ON ms.society_id=b.society_id AND ms.enabled
WHERE b.society_id=$1 AND b.id>$2
AND v.outstanding_amount_paise>0
AND v.payment_claim_status IS DISTINCT FROM 'pending'
AND ($3::timestamptz AT TIME ZONE b.timezone)::date IN (b.due_date-3,b.due_date,b.due_date+7)
ORDER BY b.id LIMIT 500
`

type ListMaintenanceReminderCandidatesParams struct {
	SocietyID int64              `db:"society_id" json:"society_id"`
	AfterID   int64              `db:"after_id" json:"after_id"`
	AsOf      pgtype.Timestamptz `db:"as_of" json:"as_of"`
}

type ListMaintenanceReminderCandidatesRow struct {
	ID       int64       `db:"id" json:"id"`
	DueDate  pgtype.Date `db:"due_date" json:"due_date"`
	Timezone string      `db:"timezone" json:"timezone"`
}

func (q *Queries) ListMaintenanceReminderCandidates(ctx context.Context, arg ListMaintenanceReminderCandidatesParams) ([]ListMaintenanceReminderCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listMaintenanceReminderCandidates, arg.SocietyID, arg.AfterID, arg.AsOf)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMaintenanceReminderCandidatesRow{}
	for rows.Next() {
		var i ListMaintenanceReminderCandidatesRow
		if err := rows.Scan(&i.ID, &i.DueDate, &i.Timezone); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
