// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: maintenance_readiness.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getMaintenanceFirstMonth = `-- name: GetMaintenanceFirstMonth :one
SELECT first_enabled_month FROM maintenance_settings WHERE society_id=$1
`

func (q *Queries) GetMaintenanceFirstMonth(ctx context.Context, societyID int64) (pgtype.Date, error) {
	row := q.db.QueryRow(ctx, getMaintenanceFirstMonth, societyID)
	var first_enabled_month pgtype.Date
	err := row.Scan(&first_enabled_month)
	return first_enabled_month, err
}

const getMaintenanceReview = `-- name: GetMaintenanceReview :one
SELECT snapshot_hash,expires_at FROM maintenance_preview_reviews WHERE token=$1 AND society_id=$2 AND actor_id=$3 AND billing_month=$4
`

type GetMaintenanceReviewParams struct {
	Token        pgtype.UUID `db:"token" json:"token"`
	SocietyID    int64       `db:"society_id" json:"society_id"`
	ActorID      int64       `db:"actor_id" json:"actor_id"`
	BillingMonth pgtype.Date `db:"billing_month" json:"billing_month"`
}

type GetMaintenanceReviewRow struct {
	SnapshotHash string             `db:"snapshot_hash" json:"snapshot_hash"`
	ExpiresAt    pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

func (q *Queries) GetMaintenanceReview(ctx context.Context, arg GetMaintenanceReviewParams) (GetMaintenanceReviewRow, error) {
	row := q.db.QueryRow(ctx, getMaintenanceReview,
		arg.Token,
		arg.SocietyID,
		arg.ActorID,
		arg.BillingMonth,
	)
	var i GetMaintenanceReviewRow
	err := row.Scan(&i.SnapshotHash, &i.ExpiresAt)
	return i, err
}

const maintenanceFlatAccess = `-- name: MaintenanceFlatAccess :one
SELECT EXISTS(SELECT 1 FROM flats f JOIN societies s ON s.id=f.society_id
WHERE f.id=$1 AND f.society_id=$2 AND s.status='active' AND s.deleted_at IS NULL AND (
 EXISTS(SELECT 1 FROM society_members m WHERE m.society_id=f.society_id AND m.user_id=$3 AND m.status='active' AND m.role IN ('owner','admin'))
 OR (f.is_active AND EXISTS(SELECT 1 FROM flat_residents r JOIN society_members m ON m.society_id=r.society_id AND m.user_id=r.user_id WHERE r.flat_id=f.id AND r.society_id=f.society_id AND r.user_id=$3 AND r.status='active' AND m.status='active' AND m.role='resident'))
))::boolean
`

type MaintenanceFlatAccessParams struct {
	ID        int64 `db:"id" json:"id"`
	SocietyID int64 `db:"society_id" json:"society_id"`
	UserID    int64 `db:"user_id" json:"user_id"`
}

func (q *Queries) MaintenanceFlatAccess(ctx context.Context, arg MaintenanceFlatAccessParams) (bool, error) {
	row := q.db.QueryRow(ctx, maintenanceFlatAccess, arg.ID, arg.SocietyID, arg.UserID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const maintenanceOutstandingBills = `-- name: MaintenanceOutstandingBills :many
SELECT b.id,b.bill_number,b.billing_month,b.due_date,v.outstanding_amount_paise,v.payment_status
FROM maintenance_bills b JOIN maintenance_bill_balances v ON v.bill_id=b.id
WHERE b.society_id=$1 AND b.flat_id=$2 AND v.outstanding_amount_paise>0 ORDER BY b.billing_month,b.id
`

type MaintenanceOutstandingBillsParams struct {
	SocietyID int64 `db:"society_id" json:"society_id"`
	FlatID    int64 `db:"flat_id" json:"flat_id"`
}

type MaintenanceOutstandingBillsRow struct {
	ID                     int64       `db:"id" json:"id"`
	BillNumber             string      `db:"bill_number" json:"bill_number"`
	BillingMonth           pgtype.Date `db:"billing_month" json:"billing_month"`
	DueDate                pgtype.Date `db:"due_date" json:"due_date"`
	OutstandingAmountPaise int64       `db:"outstanding_amount_paise" json:"outstanding_amount_paise"`
	PaymentStatus          string      `db:"payment_status" json:"payment_status"`
}

func (q *Queries) MaintenanceOutstandingBills(ctx context.Context, arg MaintenanceOutstandingBillsParams) ([]MaintenanceOutstandingBillsRow, error) {
	rows, err := q.db.Query(ctx, maintenanceOutstandingBills, arg.SocietyID, arg.FlatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MaintenanceOutstandingBillsRow{}
	for rows.Next() {
		var i MaintenanceOutstandingBillsRow
		if err := rows.Scan(
			&i.ID,
			&i.BillNumber,
			&i.BillingMonth,
			&i.DueDate,
			&i.OutstandingAmountPaise,
			&i.PaymentStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maintenancePendingClaimsCount = `-- name: MaintenancePendingClaimsCount :one
SELECT count(*)::bigint FROM maintenance_payment_claims WHERE status='pending'
`

func (q *Queries) MaintenancePendingClaimsCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, maintenancePendingClaimsCount)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const saveMaintenanceReview = `-- name: SaveMaintenanceReview :exec
INSERT INTO maintenance_preview_reviews(token,society_id,actor_id,billing_month,snapshot_hash,expires_at) VALUES($1,$2,$3,$4,$5,$6)
`

type SaveMaintenanceReviewParams struct {
	Token        pgtype.UUID        `db:"token" json:"token"`
	SocietyID    int64              `db:"society_id" json:"society_id"`
	ActorID      int64              `db:"actor_id" json:"actor_id"`
	BillingMonth pgtype.Date        `db:"billing_month" json:"billing_month"`
	SnapshotHash string             `db:"snapshot_hash" json:"snapshot_hash"`
	ExpiresAt    pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

func (q *Queries) SaveMaintenanceReview(ctx context.Context, arg SaveMaintenanceReviewParams) error {
	_, err := q.db.Exec(ctx, saveMaintenanceReview,
		arg.Token,
		arg.SocietyID,
		arg.ActorID,
		arg.BillingMonth,
		arg.SnapshotHash,
		arg.ExpiresAt,
	)
	return err
}

const setMaintenanceFirstMonth = `-- name: SetMaintenanceFirstMonth :exec
UPDATE maintenance_settings SET first_enabled_month=$2 WHERE society_id=$1 AND first_enabled_month IS NULL
`

type SetMaintenanceFirstMonthParams struct {
	SocietyID         int64       `db:"society_id" json:"society_id"`
	FirstEnabledMonth pgtype.Date `db:"first_enabled_month" json:"first_enabled_month"`
}

func (q *Queries) SetMaintenanceFirstMonth(ctx context.Context, arg SetMaintenanceFirstMonthParams) error {
	_, err := q.db.Exec(ctx, setMaintenanceFirstMonth, arg.SocietyID, arg.FirstEnabledMonth)
	return err
}
