// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: maintenance_payments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const closeUPIRequests = `-- name: CloseUPIRequests :exec
UPDATE maintenance_payment_requests SET state='closed' WHERE society_id=$1 AND bill_id=$2 AND state<>'closed'
`

type CloseUPIRequestsParams struct {
	SocietyID int64 `db:"society_id" json:"society_id"`
	BillID    int64 `db:"bill_id" json:"bill_id"`
}

func (q *Queries) CloseUPIRequests(ctx context.Context, arg CloseUPIRequestsParams) error {
	_, err := q.db.Exec(ctx, closeUPIRequests, arg.SocietyID, arg.BillID)
	return err
}

const enqueueUPIEvent = `-- name: EnqueueUPIEvent :exec
INSERT INTO maintenance_notification_deliveries(bill_id,user_id,event_type,event_key,audience,event_data)
SELECT $1,m.user_id,$2,$3,$4,$5
FROM society_members m WHERE m.society_id=$6 AND m.status='active' AND
(($4='admin' AND m.role IN ('owner','admin')) OR
($4='resident' AND EXISTS(SELECT 1 FROM flat_residents r JOIN maintenance_bills b ON b.flat_id=r.flat_id AND b.society_id=r.society_id WHERE b.id=$1 AND r.user_id=m.user_id AND r.status='active')))
ON CONFLICT(user_id,event_key) DO NOTHING
`

type EnqueueUPIEventParams struct {
	BillID    int64  `db:"bill_id" json:"bill_id"`
	EventType string `db:"event_type" json:"event_type"`
	EventKey  string `db:"event_key" json:"event_key"`
	Audience  string `db:"audience" json:"audience"`
	EventData []byte `db:"event_data" json:"event_data"`
	SocietyID int64  `db:"society_id" json:"society_id"`
}

func (q *Queries) EnqueueUPIEvent(ctx context.Context, arg EnqueueUPIEventParams) error {
	_, err := q.db.Exec(ctx, enqueueUPIEvent,
		arg.BillID,
		arg.EventType,
		arg.EventKey,
		arg.Audience,
		arg.EventData,
		arg.SocietyID,
	)
	return err
}

const getActiveUPIPayment = `-- name: GetActiveUPIPayment :one
SELECT id, society_id, bill_id, claim_id, payer_id, settings_version, amount_paise, reference, credit_date, receipt_number, verified_by, verified_at, status, reversed_by, reversed_at, reversal_reason, evidence_reference FROM maintenance_payments WHERE society_id=$1 AND bill_id=$2 AND status='verified'
`

type GetActiveUPIPaymentParams struct {
	SocietyID int64 `db:"society_id" json:"society_id"`
	BillID    int64 `db:"bill_id" json:"bill_id"`
}

func (q *Queries) GetActiveUPIPayment(ctx context.Context, arg GetActiveUPIPaymentParams) (MaintenancePayment, error) {
	row := q.db.QueryRow(ctx, getActiveUPIPayment, arg.SocietyID, arg.BillID)
	var i MaintenancePayment
	err := row.Scan(
		&i.ID,
		&i.SocietyID,
		&i.BillID,
		&i.ClaimID,
		&i.PayerID,
		&i.SettingsVersion,
		&i.AmountPaise,
		&i.Reference,
		&i.CreditDate,
		&i.ReceiptNumber,
		&i.VerifiedBy,
		&i.VerifiedAt,
		&i.Status,
		&i.ReversedBy,
		&i.ReversedAt,
		&i.ReversalReason,
		&i.EvidenceReference,
	)
	return i, err
}

const getActiveUPIRequest = `-- name: GetActiveUPIRequest :one
SELECT id, society_id, bill_id, settings_version, amount_paise, reference, state, created_by, created_at FROM maintenance_payment_requests WHERE society_id=$1 AND bill_id=$2 AND state='active'
`

type GetActiveUPIRequestParams struct {
	SocietyID int64 `db:"society_id" json:"society_id"`
	BillID    int64 `db:"bill_id" json:"bill_id"`
}

func (q *Queries) GetActiveUPIRequest(ctx context.Context, arg GetActiveUPIRequestParams) (MaintenancePaymentRequest, error) {
	row := q.db.QueryRow(ctx, getActiveUPIRequest, arg.SocietyID, arg.BillID)
	var i MaintenancePaymentRequest
	err := row.Scan(
		&i.ID,
		&i.SocietyID,
		&i.BillID,
		&i.SettingsVersion,
		&i.AmountPaise,
		&i.Reference,
		&i.State,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getPaymentBill = `-- name: GetPaymentBill :one
SELECT id, run_id, society_id, flat_id, billing_month, bill_number, due_date, timezone, total_paise, snapshot, billed_party, created_at, issuer_snapshot FROM maintenance_bills WHERE society_id=$1 AND id=$2
`

type GetPaymentBillParams struct {
	SocietyID int64 `db:"society_id" json:"society_id"`
	ID        int64 `db:"id" json:"id"`
}

func (q *Queries) GetPaymentBill(ctx context.Context, arg GetPaymentBillParams) (MaintenanceBill, error) {
	row := q.db.QueryRow(ctx, getPaymentBill, arg.SocietyID, arg.ID)
	var i MaintenanceBill
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.SocietyID,
		&i.FlatID,
		&i.BillingMonth,
		&i.BillNumber,
		&i.DueDate,
		&i.Timezone,
		&i.TotalPaise,
		&i.Snapshot,
		&i.BilledParty,
		&i.CreatedAt,
		&i.IssuerSnapshot,
	)
	return i, err
}

const getPendingUPIClaim = `-- name: GetPendingUPIClaim :one
SELECT id, society_id, bill_id, request_id, submitted_by, reference, payment_date, status, reviewed_by, reviewed_at, reason, created_at FROM maintenance_payment_claims WHERE society_id=$1 AND bill_id=$2 AND status='pending'
`

type GetPendingUPIClaimParams struct {
	SocietyID int64 `db:"society_id" json:"society_id"`
	BillID    int64 `db:"bill_id" json:"bill_id"`
}

func (q *Queries) GetPendingUPIClaim(ctx context.Context, arg GetPendingUPIClaimParams) (MaintenancePaymentClaim, error) {
	row := q.db.QueryRow(ctx, getPendingUPIClaim, arg.SocietyID, arg.BillID)
	var i MaintenancePaymentClaim
	err := row.Scan(
		&i.ID,
		&i.SocietyID,
		&i.BillID,
		&i.RequestID,
		&i.SubmittedBy,
		&i.Reference,
		&i.PaymentDate,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const getUPIClaim = `-- name: GetUPIClaim :one
SELECT id, society_id, bill_id, request_id, submitted_by, reference, payment_date, status, reviewed_by, reviewed_at, reason, created_at FROM maintenance_payment_claims WHERE society_id=$1 AND id=$2
`

type GetUPIClaimParams struct {
	SocietyID int64 `db:"society_id" json:"society_id"`
	ID        int64 `db:"id" json:"id"`
}

func (q *Queries) GetUPIClaim(ctx context.Context, arg GetUPIClaimParams) (MaintenancePaymentClaim, error) {
	row := q.db.QueryRow(ctx, getUPIClaim, arg.SocietyID, arg.ID)
	var i MaintenancePaymentClaim
	err := row.Scan(
		&i.ID,
		&i.SocietyID,
		&i.BillID,
		&i.RequestID,
		&i.SubmittedBy,
		&i.Reference,
		&i.PaymentDate,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const getUPIIdempotency = `-- name: GetUPIIdempotency :one
SELECT society_id, actor_id, operation, key, request_hash, response, created_at FROM maintenance_payment_idempotency WHERE society_id=$1 AND actor_id=$2 AND operation=$3 AND key=$4
`

type GetUPIIdempotencyParams struct {
	SocietyID int64  `db:"society_id" json:"society_id"`
	ActorID   int64  `db:"actor_id" json:"actor_id"`
	Operation string `db:"operation" json:"operation"`
	Key       string `db:"key" json:"key"`
}

func (q *Queries) GetUPIIdempotency(ctx context.Context, arg GetUPIIdempotencyParams) (MaintenancePaymentIdempotency, error) {
	row := q.db.QueryRow(ctx, getUPIIdempotency,
		arg.SocietyID,
		arg.ActorID,
		arg.Operation,
		arg.Key,
	)
	var i MaintenancePaymentIdempotency
	err := row.Scan(
		&i.SocietyID,
		&i.ActorID,
		&i.Operation,
		&i.Key,
		&i.RequestHash,
		&i.Response,
		&i.CreatedAt,
	)
	return i, err
}

const getUPIPayment = `-- name: GetUPIPayment :one
SELECT id, society_id, bill_id, claim_id, payer_id, settings_version, amount_paise, reference, credit_date, receipt_number, verified_by, verified_at, status, reversed_by, reversed_at, reversal_reason, evidence_reference FROM maintenance_payments WHERE society_id=$1 AND id=$2
`

type GetUPIPaymentParams struct {
	SocietyID int64 `db:"society_id" json:"society_id"`
	ID        int64 `db:"id" json:"id"`
}

func (q *Queries) GetUPIPayment(ctx context.Context, arg GetUPIPaymentParams) (MaintenancePayment, error) {
	row := q.db.QueryRow(ctx, getUPIPayment, arg.SocietyID, arg.ID)
	var i MaintenancePayment
	err := row.Scan(
		&i.ID,
		&i.SocietyID,
		&i.BillID,
		&i.ClaimID,
		&i.PayerID,
		&i.SettingsVersion,
		&i.AmountPaise,
		&i.Reference,
		&i.CreditDate,
		&i.ReceiptNumber,
		&i.VerifiedBy,
		&i.VerifiedAt,
		&i.Status,
		&i.ReversedBy,
		&i.ReversedAt,
		&i.ReversalReason,
		&i.EvidenceReference,
	)
	return i, err
}

const getUPIReport = `-- name: GetUPIReport :one
SELECT r.id, r.society_id, r.bill_id, r.request_id, r.reported_by, r.reference, r.amount_paise, r.payment_date, r.explanation, r.fingerprint, r.status, r.resolution_note, r.updated_by, r.updated_at, r.created_at, b.bill_number FROM maintenance_payment_reports r
JOIN maintenance_bills b ON b.id = r.bill_id AND b.society_id = r.society_id
WHERE r.society_id=$1 AND r.id=$2
`

type GetUPIReportParams struct {
	SocietyID int64 `db:"society_id" json:"society_id"`
	ID        int64 `db:"id" json:"id"`
}

type GetUPIReportRow struct {
	MaintenancePaymentReport MaintenancePaymentReport `db:"maintenance_payment_report" json:"maintenance_payment_report"`
	BillNumber               string                   `db:"bill_number" json:"bill_number"`
}

func (q *Queries) GetUPIReport(ctx context.Context, arg GetUPIReportParams) (GetUPIReportRow, error) {
	row := q.db.QueryRow(ctx, getUPIReport, arg.SocietyID, arg.ID)
	var i GetUPIReportRow
	err := row.Scan(
		&i.MaintenancePaymentReport.ID,
		&i.MaintenancePaymentReport.SocietyID,
		&i.MaintenancePaymentReport.BillID,
		&i.MaintenancePaymentReport.RequestID,
		&i.MaintenancePaymentReport.ReportedBy,
		&i.MaintenancePaymentReport.Reference,
		&i.MaintenancePaymentReport.AmountPaise,
		&i.MaintenancePaymentReport.PaymentDate,
		&i.MaintenancePaymentReport.Explanation,
		&i.MaintenancePaymentReport.Fingerprint,
		&i.MaintenancePaymentReport.Status,
		&i.MaintenancePaymentReport.ResolutionNote,
		&i.MaintenancePaymentReport.UpdatedBy,
		&i.MaintenancePaymentReport.UpdatedAt,
		&i.MaintenancePaymentReport.CreatedAt,
		&i.BillNumber,
	)
	return i, err
}

const getUPIReportByFingerprint = `-- name: GetUPIReportByFingerprint :one
SELECT id, society_id, bill_id, request_id, reported_by, reference, amount_paise, payment_date, explanation, fingerprint, status, resolution_note, updated_by, updated_at, created_at FROM maintenance_payment_reports WHERE society_id=$1 AND reported_by=$2 AND fingerprint=$3
`

type GetUPIReportByFingerprintParams struct {
	SocietyID   int64  `db:"society_id" json:"society_id"`
	ReportedBy  int64  `db:"reported_by" json:"reported_by"`
	Fingerprint string `db:"fingerprint" json:"fingerprint"`
}

func (q *Queries) GetUPIReportByFingerprint(ctx context.Context, arg GetUPIReportByFingerprintParams) (MaintenancePaymentReport, error) {
	row := q.db.QueryRow(ctx, getUPIReportByFingerprint, arg.SocietyID, arg.ReportedBy, arg.Fingerprint)
	var i MaintenancePaymentReport
	err := row.Scan(
		&i.ID,
		&i.SocietyID,
		&i.BillID,
		&i.RequestID,
		&i.ReportedBy,
		&i.Reference,
		&i.AmountPaise,
		&i.PaymentDate,
		&i.Explanation,
		&i.Fingerprint,
		&i.Status,
		&i.ResolutionNote,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUPIRequest = `-- name: GetUPIRequest :one
SELECT id, society_id, bill_id, settings_version, amount_paise, reference, state, created_by, created_at FROM maintenance_payment_requests WHERE society_id=$1 AND id=$2
`

type GetUPIRequestParams struct {
	SocietyID int64       `db:"society_id" json:"society_id"`
	ID        pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) GetUPIRequest(ctx context.Context, arg GetUPIRequestParams) (MaintenancePaymentRequest, error) {
	row := q.db.QueryRow(ctx, getUPIRequest, arg.SocietyID, arg.ID)
	var i MaintenancePaymentRequest
	err := row.Scan(
		&i.ID,
		&i.SocietyID,
		&i.BillID,
		&i.SettingsVersion,
		&i.AmountPaise,
		&i.Reference,
		&i.State,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getUPISettings = `-- name: GetUPISettings :one
SELECT v.society_id, v.version, v.enabled, v.upi_id, v.payee_name, v.created_by, v.created_at FROM maintenance_payment_settings s JOIN maintenance_payment_settings_versions v USING(society_id,version) WHERE s.society_id=$1
`

func (q *Queries) GetUPISettings(ctx context.Context, societyID int64) (MaintenancePaymentSettingsVersion, error) {
	row := q.db.QueryRow(ctx, getUPISettings, societyID)
	var i MaintenancePaymentSettingsVersion
	err := row.Scan(
		&i.SocietyID,
		&i.Version,
		&i.Enabled,
		&i.UpiID,
		&i.PayeeName,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getUPISettingsVersion = `-- name: GetUPISettingsVersion :one
SELECT society_id, version, enabled, upi_id, payee_name, created_by, created_at FROM maintenance_payment_settings_versions WHERE society_id=$1 AND version=$2
`

type GetUPISettingsVersionParams struct {
	SocietyID int64 `db:"society_id" json:"society_id"`
	Version   int64 `db:"version" json:"version"`
}

func (q *Queries) GetUPISettingsVersion(ctx context.Context, arg GetUPISettingsVersionParams) (MaintenancePaymentSettingsVersion, error) {
	row := q.db.QueryRow(ctx, getUPISettingsVersion, arg.SocietyID, arg.Version)
	var i MaintenancePaymentSettingsVersion
	err := row.Scan(
		&i.SocietyID,
		&i.Version,
		&i.Enabled,
		&i.UpiID,
		&i.PayeeName,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const hasReversedUPIReference = `-- name: HasReversedUPIReference :one
SELECT EXISTS(SELECT 1 FROM maintenance_payments WHERE society_id=$1 AND reference=$2 AND status='reversed')::boolean
`

type HasReversedUPIReferenceParams struct {
	SocietyID int64  `db:"society_id" json:"society_id"`
	Reference string `db:"reference" json:"reference"`
}

func (q *Queries) HasReversedUPIReference(ctx context.Context, arg HasReversedUPIReferenceParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasReversedUPIReference, arg.SocietyID, arg.Reference)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const insertUPIAudit = `-- name: InsertUPIAudit :exec
INSERT INTO maintenance_payment_audit_events(society_id,bill_id,actor_id,action,entity_id,details) VALUES($1,$2,$3,$4,$5,$6)
`

type InsertUPIAuditParams struct {
	SocietyID int64  `db:"society_id" json:"society_id"`
	BillID    *int64 `db:"bill_id" json:"bill_id"`
	ActorID   int64  `db:"actor_id" json:"actor_id"`
	Action    string `db:"action" json:"action"`
	EntityID  string `db:"entity_id" json:"entity_id"`
	Details   []byte `db:"details" json:"details"`
}

func (q *Queries) InsertUPIAudit(ctx context.Context, arg InsertUPIAuditParams) error {
	_, err := q.db.Exec(ctx, insertUPIAudit,
		arg.SocietyID,
		arg.BillID,
		arg.ActorID,
		arg.Action,
		arg.EntityID,
		arg.Details,
	)
	return err
}

const insertUPIClaim = `-- name: InsertUPIClaim :one
INSERT INTO maintenance_payment_claims(society_id,bill_id,request_id,submitted_by,reference,payment_date) VALUES($1,$2,$3,$4,$5,$6) RETURNING id, society_id, bill_id, request_id, submitted_by, reference, payment_date, status, reviewed_by, reviewed_at, reason, created_at
`

type InsertUPIClaimParams struct {
	SocietyID   int64       `db:"society_id" json:"society_id"`
	BillID      int64       `db:"bill_id" json:"bill_id"`
	RequestID   pgtype.UUID `db:"request_id" json:"request_id"`
	SubmittedBy int64       `db:"submitted_by" json:"submitted_by"`
	Reference   string      `db:"reference" json:"reference"`
	PaymentDate pgtype.Date `db:"payment_date" json:"payment_date"`
}

func (q *Queries) InsertUPIClaim(ctx context.Context, arg InsertUPIClaimParams) (MaintenancePaymentClaim, error) {
	row := q.db.QueryRow(ctx, insertUPIClaim,
		arg.SocietyID,
		arg.BillID,
		arg.RequestID,
		arg.SubmittedBy,
		arg.Reference,
		arg.PaymentDate,
	)
	var i MaintenancePaymentClaim
	err := row.Scan(
		&i.ID,
		&i.SocietyID,
		&i.BillID,
		&i.RequestID,
		&i.SubmittedBy,
		&i.Reference,
		&i.PaymentDate,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const insertUPIIdempotency = `-- name: InsertUPIIdempotency :exec
INSERT INTO maintenance_payment_idempotency(society_id,actor_id,operation,key,request_hash,response) VALUES($1,$2,$3,$4,$5,$6)
`

type InsertUPIIdempotencyParams struct {
	SocietyID   int64  `db:"society_id" json:"society_id"`
	ActorID     int64  `db:"actor_id" json:"actor_id"`
	Operation   string `db:"operation" json:"operation"`
	Key         string `db:"key" json:"key"`
	RequestHash string `db:"request_hash" json:"request_hash"`
	Response    []byte `db:"response" json:"response"`
}

func (q *Queries) InsertUPIIdempotency(ctx context.Context, arg InsertUPIIdempotencyParams) error {
	_, err := q.db.Exec(ctx, insertUPIIdempotency,
		arg.SocietyID,
		arg.ActorID,
		arg.Operation,
		arg.Key,
		arg.RequestHash,
		arg.Response,
	)
	return err
}

const insertUPILedger = `-- name: InsertUPILedger :exec
INSERT INTO maintenance_payment_ledger(society_id,bill_id,payment_id,kind,amount_paise,actor_id) VALUES($1,$2,$3,$4,$5,$6)
`

type InsertUPILedgerParams struct {
	SocietyID   int64  `db:"society_id" json:"society_id"`
	BillID      int64  `db:"bill_id" json:"bill_id"`
	PaymentID   int64  `db:"payment_id" json:"payment_id"`
	Kind        string `db:"kind" json:"kind"`
	AmountPaise int64  `db:"amount_paise" json:"amount_paise"`
	ActorID     int64  `db:"actor_id" json:"actor_id"`
}

func (q *Queries) InsertUPILedger(ctx context.Context, arg InsertUPILedgerParams) error {
	_, err := q.db.Exec(ctx, insertUPILedger,
		arg.SocietyID,
		arg.BillID,
		arg.PaymentID,
		arg.Kind,
		arg.AmountPaise,
		arg.ActorID,
	)
	return err
}

const insertUPIPayment = `-- name: InsertUPIPayment :one
INSERT INTO maintenance_payments(society_id,bill_id,claim_id,payer_id,settings_version,amount_paise,reference,credit_date,receipt_number,verified_by,evidence_reference)
VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING id, society_id, bill_id, claim_id, payer_id, settings_version, amount_paise, reference, credit_date, receipt_number, verified_by, verified_at, status, reversed_by, reversed_at, reversal_reason, evidence_reference
`

type InsertUPIPaymentParams struct {
	SocietyID         int64       `db:"society_id" json:"society_id"`
	BillID            int64       `db:"bill_id" json:"bill_id"`
	ClaimID           *int64      `db:"claim_id" json:"claim_id"`
	PayerID           *int64      `db:"payer_id" json:"payer_id"`
	SettingsVersion   int64       `db:"settings_version" json:"settings_version"`
	AmountPaise       int64       `db:"amount_paise" json:"amount_paise"`
	Reference         string      `db:"reference" json:"reference"`
	CreditDate        pgtype.Date `db:"credit_date" json:"credit_date"`
	ReceiptNumber     pgtype.UUID `db:"receipt_number" json:"receipt_number"`
	VerifiedBy        int64       `db:"verified_by" json:"verified_by"`
	EvidenceReference string      `db:"evidence_reference" json:"evidence_reference"`
}

func (q *Queries) InsertUPIPayment(ctx context.Context, arg InsertUPIPaymentParams) (MaintenancePayment, error) {
	row := q.db.QueryRow(ctx, insertUPIPayment,
		arg.SocietyID,
		arg.BillID,
		arg.ClaimID,
		arg.PayerID,
		arg.SettingsVersion,
		arg.AmountPaise,
		arg.Reference,
		arg.CreditDate,
		arg.ReceiptNumber,
		arg.VerifiedBy,
		arg.EvidenceReference,
	)
	var i MaintenancePayment
	err := row.Scan(
		&i.ID,
		&i.SocietyID,
		&i.BillID,
		&i.ClaimID,
		&i.PayerID,
		&i.SettingsVersion,
		&i.AmountPaise,
		&i.Reference,
		&i.CreditDate,
		&i.ReceiptNumber,
		&i.VerifiedBy,
		&i.VerifiedAt,
		&i.Status,
		&i.ReversedBy,
		&i.ReversedAt,
		&i.ReversalReason,
		&i.EvidenceReference,
	)
	return i, err
}

const insertUPIReport = `-- name: InsertUPIReport :one
INSERT INTO maintenance_payment_reports(society_id,bill_id,request_id,reported_by,reference,amount_paise,payment_date,explanation,fingerprint)
VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) ON CONFLICT(society_id,reported_by,fingerprint) DO NOTHING RETURNING id, society_id, bill_id, request_id, reported_by, reference, amount_paise, payment_date, explanation, fingerprint, status, resolution_note, updated_by, updated_at, created_at
`

type InsertUPIReportParams struct {
	SocietyID   int64       `db:"society_id" json:"society_id"`
	BillID      int64       `db:"bill_id" json:"bill_id"`
	RequestID   pgtype.UUID `db:"request_id" json:"request_id"`
	ReportedBy  int64       `db:"reported_by" json:"reported_by"`
	Reference   string      `db:"reference" json:"reference"`
	AmountPaise int64       `db:"amount_paise" json:"amount_paise"`
	PaymentDate pgtype.Date `db:"payment_date" json:"payment_date"`
	Explanation string      `db:"explanation" json:"explanation"`
	Fingerprint string      `db:"fingerprint" json:"fingerprint"`
}

func (q *Queries) InsertUPIReport(ctx context.Context, arg InsertUPIReportParams) (MaintenancePaymentReport, error) {
	row := q.db.QueryRow(ctx, insertUPIReport,
		arg.SocietyID,
		arg.BillID,
		arg.RequestID,
		arg.ReportedBy,
		arg.Reference,
		arg.AmountPaise,
		arg.PaymentDate,
		arg.Explanation,
		arg.Fingerprint,
	)
	var i MaintenancePaymentReport
	err := row.Scan(
		&i.ID,
		&i.SocietyID,
		&i.BillID,
		&i.RequestID,
		&i.ReportedBy,
		&i.Reference,
		&i.AmountPaise,
		&i.PaymentDate,
		&i.Explanation,
		&i.Fingerprint,
		&i.Status,
		&i.ResolutionNote,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertUPIRequest = `-- name: InsertUPIRequest :one
INSERT INTO maintenance_payment_requests(id,society_id,bill_id,settings_version,amount_paise,reference,created_by) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING id, society_id, bill_id, settings_version, amount_paise, reference, state, created_by, created_at
`

type InsertUPIRequestParams struct {
	ID              pgtype.UUID `db:"id" json:"id"`
	SocietyID       int64       `db:"society_id" json:"society_id"`
	BillID          int64       `db:"bill_id" json:"bill_id"`
	SettingsVersion int64       `db:"settings_version" json:"settings_version"`
	AmountPaise     int64       `db:"amount_paise" json:"amount_paise"`
	Reference       string      `db:"reference" json:"reference"`
	CreatedBy       int64       `db:"created_by" json:"created_by"`
}

func (q *Queries) InsertUPIRequest(ctx context.Context, arg InsertUPIRequestParams) (MaintenancePaymentRequest, error) {
	row := q.db.QueryRow(ctx, insertUPIRequest,
		arg.ID,
		arg.SocietyID,
		arg.BillID,
		arg.SettingsVersion,
		arg.AmountPaise,
		arg.Reference,
		arg.CreatedBy,
	)
	var i MaintenancePaymentRequest
	err := row.Scan(
		&i.ID,
		&i.SocietyID,
		&i.BillID,
		&i.SettingsVersion,
		&i.AmountPaise,
		&i.Reference,
		&i.State,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const insertUPISettingsVersion = `-- name: InsertUPISettingsVersion :one
INSERT INTO maintenance_payment_settings_versions(society_id,version,enabled,upi_id,payee_name,created_by) VALUES($1,$2,$3,$4,$5,$6) RETURNING society_id, version, enabled, upi_id, payee_name, created_by, created_at
`

type InsertUPISettingsVersionParams struct {
	SocietyID int64  `db:"society_id" json:"society_id"`
	Version   int64  `db:"version" json:"version"`
	Enabled   bool   `db:"enabled" json:"enabled"`
	UpiID     string `db:"upi_id" json:"upi_id"`
	PayeeName string `db:"payee_name" json:"payee_name"`
	CreatedBy int64  `db:"created_by" json:"created_by"`
}

func (q *Queries) InsertUPISettingsVersion(ctx context.Context, arg InsertUPISettingsVersionParams) (MaintenancePaymentSettingsVersion, error) {
	row := q.db.QueryRow(ctx, insertUPISettingsVersion,
		arg.SocietyID,
		arg.Version,
		arg.Enabled,
		arg.UpiID,
		arg.PayeeName,
		arg.CreatedBy,
	)
	var i MaintenancePaymentSettingsVersion
	err := row.Scan(
		&i.SocietyID,
		&i.Version,
		&i.Enabled,
		&i.UpiID,
		&i.PayeeName,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listUPIAudit = `-- name: ListUPIAudit :many
SELECT id, society_id, bill_id, actor_id, action, entity_id, details, created_at FROM maintenance_payment_audit_events WHERE society_id=$1 AND ($2::bigint=0 OR bill_id=$2) AND ($3::bigint=0 OR id<$3) ORDER BY id DESC LIMIT $4
`

type ListUPIAuditParams struct {
	SocietyID int64 `db:"society_id" json:"society_id"`
	BillID    int64 `db:"bill_id" json:"bill_id"`
	BeforeID  int64 `db:"before_id" json:"before_id"`
	Limit     int32 `db:"limit" json:"limit"`
}

func (q *Queries) ListUPIAudit(ctx context.Context, arg ListUPIAuditParams) ([]MaintenancePaymentAuditEvent, error) {
	rows, err := q.db.Query(ctx, listUPIAudit,
		arg.SocietyID,
		arg.BillID,
		arg.BeforeID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MaintenancePaymentAuditEvent{}
	for rows.Next() {
		var i MaintenancePaymentAuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.SocietyID,
			&i.BillID,
			&i.ActorID,
			&i.Action,
			&i.EntityID,
			&i.Details,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUPIClaims = `-- name: ListUPIClaims :many
SELECT id, society_id, bill_id, request_id, submitted_by, reference, payment_date, status, reviewed_by, reviewed_at, reason, created_at FROM maintenance_payment_claims c WHERE c.society_id=$1
AND ($2::bigint=0 OR c.submitted_by=$2)
AND ($3::text='' OR c.status=$3)
AND ($4::text='' OR c.reference=$4)
AND ($5::bigint=0 OR c.id<$5)
AND ($6::bigint=0 OR c.bill_id=$6)
AND EXISTS(
  SELECT 1 FROM maintenance_bills fb
  JOIN flats bf ON bf.id=fb.flat_id AND bf.society_id=fb.society_id AND bf.is_active
  WHERE fb.id=c.bill_id AND fb.society_id=c.society_id
  AND ($7::bigint=0 OR fb.flat_id=$7)
  AND ($8::date IS NULL OR fb.billing_month=$8)
  AND ($9::text IS NULL OR COALESCE(bf.block, '') ILIKE '%' || $9::text || '%')
  AND ($10::text IS NULL OR bf.flat_number ILIKE '%' || $10::text || '%')
  AND (
    $11::text = ''
    OR bf.flat_number ILIKE '%' || $11::text || '%'
    OR COALESCE(bf.block, '') ILIKE '%' || $11::text || '%'
  )
)
AND ($2::bigint=0 OR EXISTS(SELECT 1 FROM maintenance_bills b JOIN flats f ON f.id=b.flat_id AND f.is_active JOIN flat_residents r ON r.flat_id=b.flat_id AND r.society_id=b.society_id JOIN society_members m ON m.society_id=r.society_id AND m.user_id=r.user_id WHERE b.id=c.bill_id AND r.user_id=$2 AND r.status='active' AND m.status='active'))
ORDER BY c.id DESC LIMIT $12
`

type ListUPIClaimsParams struct {
	SocietyID    int64       `db:"society_id" json:"society_id"`
	UserID       int64       `db:"user_id" json:"user_id"`
	Status       string      `db:"status" json:"status"`
	Reference    string      `db:"reference" json:"reference"`
	BeforeID     int64       `db:"before_id" json:"before_id"`
	BillID       int64       `db:"bill_id" json:"bill_id"`
	FlatID       int64       `db:"flat_id" json:"flat_id"`
	BillingMonth pgtype.Date `db:"billing_month" json:"billing_month"`
	Block        *string     `db:"block" json:"block"`
	FlatNumber   *string     `db:"flat_number" json:"flat_number"`
	Search       string      `db:"search" json:"search"`
	Limit        int32       `db:"limit" json:"limit"`
}

func (q *Queries) ListUPIClaims(ctx context.Context, arg ListUPIClaimsParams) ([]MaintenancePaymentClaim, error) {
	rows, err := q.db.Query(ctx, listUPIClaims,
		arg.SocietyID,
		arg.UserID,
		arg.Status,
		arg.Reference,
		arg.BeforeID,
		arg.BillID,
		arg.FlatID,
		arg.BillingMonth,
		arg.Block,
		arg.FlatNumber,
		arg.Search,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MaintenancePaymentClaim{}
	for rows.Next() {
		var i MaintenancePaymentClaim
		if err := rows.Scan(
			&i.ID,
			&i.SocietyID,
			&i.BillID,
			&i.RequestID,
			&i.SubmittedBy,
			&i.Reference,
			&i.PaymentDate,
			&i.Status,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUPIPayments = `-- name: ListUPIPayments :many
SELECT p.id, p.society_id, p.bill_id, p.claim_id, p.payer_id, p.settings_version, p.amount_paise, p.reference, p.credit_date, p.receipt_number, p.verified_by, p.verified_at, p.status, p.reversed_by, p.reversed_at, p.reversal_reason, p.evidence_reference FROM maintenance_payments p WHERE p.society_id=$1
AND ($2::text='' OR p.status=$2)
AND ($3::text='' OR p.reference=$3)
AND ($4::bigint=0 OR p.id<$4)
AND ($5::bigint=0 OR p.bill_id=$5)
AND EXISTS(
  SELECT 1 FROM maintenance_bills fb
  JOIN flats bf ON bf.id=fb.flat_id AND bf.society_id=fb.society_id AND bf.is_active
  WHERE fb.id=p.bill_id AND fb.society_id=p.society_id
  AND ($6::bigint=0 OR fb.flat_id=$6)
  AND ($7::date IS NULL OR fb.billing_month=$7)
  AND ($8::text IS NULL OR COALESCE(bf.block, '') ILIKE '%' || $8::text || '%')
  AND ($9::text IS NULL OR bf.flat_number ILIKE '%' || $9::text || '%')
  AND (
    $10::text = ''
    OR bf.flat_number ILIKE '%' || $10::text || '%'
    OR COALESCE(bf.block, '') ILIKE '%' || $10::text || '%'
  )
)
AND ($11::bigint=0 OR EXISTS(SELECT 1 FROM maintenance_bills b JOIN flats f ON f.id=b.flat_id AND f.is_active JOIN flat_residents r ON r.flat_id=b.flat_id AND r.society_id=b.society_id JOIN society_members m ON m.society_id=r.society_id AND m.user_id=r.user_id WHERE b.id=p.bill_id AND r.user_id=$11 AND r.status='active' AND m.status='active'))
ORDER BY p.id DESC LIMIT $12
`

type ListUPIPaymentsParams struct {
	SocietyID    int64       `db:"society_id" json:"society_id"`
	Status       string      `db:"status" json:"status"`
	Reference    string      `db:"reference" json:"reference"`
	BeforeID     int64       `db:"before_id" json:"before_id"`
	BillID       int64       `db:"bill_id" json:"bill_id"`
	FlatID       int64       `db:"flat_id" json:"flat_id"`
	BillingMonth pgtype.Date `db:"billing_month" json:"billing_month"`
	Block        *string     `db:"block" json:"block"`
	FlatNumber   *string     `db:"flat_number" json:"flat_number"`
	Search       string      `db:"search" json:"search"`
	UserID       int64       `db:"user_id" json:"user_id"`
	Limit        int32       `db:"limit" json:"limit"`
}

func (q *Queries) ListUPIPayments(ctx context.Context, arg ListUPIPaymentsParams) ([]MaintenancePayment, error) {
	rows, err := q.db.Query(ctx, listUPIPayments,
		arg.SocietyID,
		arg.Status,
		arg.Reference,
		arg.BeforeID,
		arg.BillID,
		arg.FlatID,
		arg.BillingMonth,
		arg.Block,
		arg.FlatNumber,
		arg.Search,
		arg.UserID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MaintenancePayment{}
	for rows.Next() {
		var i MaintenancePayment
		if err := rows.Scan(
			&i.ID,
			&i.SocietyID,
			&i.BillID,
			&i.ClaimID,
			&i.PayerID,
			&i.SettingsVersion,
			&i.AmountPaise,
			&i.Reference,
			&i.CreditDate,
			&i.ReceiptNumber,
			&i.VerifiedBy,
			&i.VerifiedAt,
			&i.Status,
			&i.ReversedBy,
			&i.ReversedAt,
			&i.ReversalReason,
			&i.EvidenceReference,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUPIReports = `-- name: ListUPIReports :many
SELECT r.id, r.society_id, r.bill_id, r.request_id, r.reported_by, r.reference, r.amount_paise, r.payment_date, r.explanation, r.fingerprint, r.status, r.resolution_note, r.updated_by, r.updated_at, r.created_at, b.bill_number FROM maintenance_payment_reports r
JOIN maintenance_bills b ON b.id = r.bill_id AND b.society_id = r.society_id
WHERE r.society_id=$1
AND ($2::bigint=0 OR r.reported_by=$2)
AND ($3::text='' OR r.status=$3)
AND ($4::bigint=0 OR r.id<$4)
AND ($2::bigint=0 OR EXISTS(SELECT 1 FROM maintenance_bills b JOIN flats f ON f.id=b.flat_id AND f.is_active JOIN flat_residents fr ON fr.flat_id=b.flat_id AND fr.society_id=b.society_id JOIN society_members m ON m.society_id=fr.society_id AND m.user_id=fr.user_id WHERE b.id=r.bill_id AND fr.user_id=$2 AND fr.status='active' AND m.status='active'))
ORDER BY r.id DESC LIMIT $5
`

type ListUPIReportsParams struct {
	SocietyID int64  `db:"society_id" json:"society_id"`
	UserID    int64  `db:"user_id" json:"user_id"`
	Status    string `db:"status" json:"status"`
	BeforeID  int64  `db:"before_id" json:"before_id"`
	Limit     int32  `db:"limit" json:"limit"`
}

type ListUPIReportsRow struct {
	MaintenancePaymentReport MaintenancePaymentReport `db:"maintenance_payment_report" json:"maintenance_payment_report"`
	BillNumber               string                   `db:"bill_number" json:"bill_number"`
}

func (q *Queries) ListUPIReports(ctx context.Context, arg ListUPIReportsParams) ([]ListUPIReportsRow, error) {
	rows, err := q.db.Query(ctx, listUPIReports,
		arg.SocietyID,
		arg.UserID,
		arg.Status,
		arg.BeforeID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUPIReportsRow{}
	for rows.Next() {
		var i ListUPIReportsRow
		if err := rows.Scan(
			&i.MaintenancePaymentReport.ID,
			&i.MaintenancePaymentReport.SocietyID,
			&i.MaintenancePaymentReport.BillID,
			&i.MaintenancePaymentReport.RequestID,
			&i.MaintenancePaymentReport.ReportedBy,
			&i.MaintenancePaymentReport.Reference,
			&i.MaintenancePaymentReport.AmountPaise,
			&i.MaintenancePaymentReport.PaymentDate,
			&i.MaintenancePaymentReport.Explanation,
			&i.MaintenancePaymentReport.Fingerprint,
			&i.MaintenancePaymentReport.Status,
			&i.MaintenancePaymentReport.ResolutionNote,
			&i.MaintenancePaymentReport.UpdatedBy,
			&i.MaintenancePaymentReport.UpdatedAt,
			&i.MaintenancePaymentReport.CreatedAt,
			&i.BillNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUPISettingsVersions = `-- name: ListUPISettingsVersions :many
SELECT society_id, version, enabled, upi_id, payee_name, created_by, created_at FROM maintenance_payment_settings_versions WHERE society_id=$1 AND ($2::bigint=0 OR version<$2) ORDER BY version DESC LIMIT $3
`

type ListUPISettingsVersionsParams struct {
	SocietyID     int64 `db:"society_id" json:"society_id"`
	BeforeVersion int64 `db:"before_version" json:"before_version"`
	Limit         int32 `db:"limit" json:"limit"`
}

func (q *Queries) ListUPISettingsVersions(ctx context.Context, arg ListUPISettingsVersionsParams) ([]MaintenancePaymentSettingsVersion, error) {
	rows, err := q.db.Query(ctx, listUPISettingsVersions, arg.SocietyID, arg.BeforeVersion, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MaintenancePaymentSettingsVersion{}
	for rows.Next() {
		var i MaintenancePaymentSettingsVersion
		if err := rows.Scan(
			&i.SocietyID,
			&i.Version,
			&i.Enabled,
			&i.UpiID,
			&i.PayeeName,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockMaintenancePaymentBill = `-- name: LockMaintenancePaymentBill :one
SELECT id, run_id, society_id, flat_id, billing_month, bill_number, due_date, timezone, total_paise, snapshot, billed_party, created_at, issuer_snapshot FROM maintenance_bills WHERE society_id=$1 AND id=$2 FOR UPDATE
`

type LockMaintenancePaymentBillParams struct {
	SocietyID int64 `db:"society_id" json:"society_id"`
	ID        int64 `db:"id" json:"id"`
}

func (q *Queries) LockMaintenancePaymentBill(ctx context.Context, arg LockMaintenancePaymentBillParams) (MaintenanceBill, error) {
	row := q.db.QueryRow(ctx, lockMaintenancePaymentBill, arg.SocietyID, arg.ID)
	var i MaintenanceBill
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.SocietyID,
		&i.FlatID,
		&i.BillingMonth,
		&i.BillNumber,
		&i.DueDate,
		&i.Timezone,
		&i.TotalPaise,
		&i.Snapshot,
		&i.BilledParty,
		&i.CreatedAt,
		&i.IssuerSnapshot,
	)
	return i, err
}

const maintenanceResidentAccess = `-- name: MaintenanceResidentAccess :one
SELECT EXISTS(SELECT 1 FROM maintenance_bills b JOIN flats f ON f.id=b.flat_id AND f.society_id=b.society_id AND f.is_active
JOIN flat_residents r ON r.flat_id=f.id AND r.society_id=f.society_id AND r.status='active'
JOIN society_members m ON m.user_id=r.user_id AND m.society_id=r.society_id AND m.status='active'
JOIN societies s ON s.id=b.society_id AND s.status='active' AND s.deleted_at IS NULL
WHERE b.society_id=$1 AND b.id=$2 AND r.user_id=$3)::boolean
`

type MaintenanceResidentAccessParams struct {
	SocietyID int64 `db:"society_id" json:"society_id"`
	ID        int64 `db:"id" json:"id"`
	UserID    int64 `db:"user_id" json:"user_id"`
}

func (q *Queries) MaintenanceResidentAccess(ctx context.Context, arg MaintenanceResidentAccessParams) (bool, error) {
	row := q.db.QueryRow(ctx, maintenanceResidentAccess, arg.SocietyID, arg.ID, arg.UserID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const pointUPISettings = `-- name: PointUPISettings :exec
INSERT INTO maintenance_payment_settings(society_id,version) VALUES($1,$2) ON CONFLICT(society_id) DO UPDATE SET version=excluded.version
`

type PointUPISettingsParams struct {
	SocietyID int64 `db:"society_id" json:"society_id"`
	Version   int64 `db:"version" json:"version"`
}

func (q *Queries) PointUPISettings(ctx context.Context, arg PointUPISettingsParams) error {
	_, err := q.db.Exec(ctx, pointUPISettings, arg.SocietyID, arg.Version)
	return err
}

const releaseUPIClaimReference = `-- name: ReleaseUPIClaimReference :exec
DELETE FROM maintenance_payment_reference_reservations WHERE society_id=$1 AND claim_id=$2
`

type ReleaseUPIClaimReferenceParams struct {
	SocietyID int64  `db:"society_id" json:"society_id"`
	ClaimID   *int64 `db:"claim_id" json:"claim_id"`
}

func (q *Queries) ReleaseUPIClaimReference(ctx context.Context, arg ReleaseUPIClaimReferenceParams) error {
	_, err := q.db.Exec(ctx, releaseUPIClaimReference, arg.SocietyID, arg.ClaimID)
	return err
}

const releaseUPIPaymentReference = `-- name: ReleaseUPIPaymentReference :exec
DELETE FROM maintenance_payment_reference_reservations WHERE society_id=$1 AND payment_id=$2
`

type ReleaseUPIPaymentReferenceParams struct {
	SocietyID int64  `db:"society_id" json:"society_id"`
	PaymentID *int64 `db:"payment_id" json:"payment_id"`
}

func (q *Queries) ReleaseUPIPaymentReference(ctx context.Context, arg ReleaseUPIPaymentReferenceParams) error {
	_, err := q.db.Exec(ctx, releaseUPIPaymentReference, arg.SocietyID, arg.PaymentID)
	return err
}

const reserveUPIReference = `-- name: ReserveUPIReference :exec
INSERT INTO maintenance_payment_reference_reservations(society_id,reference,bill_id,claim_id,payment_id) VALUES($1,$2,$3,$4,$5)
`

type ReserveUPIReferenceParams struct {
	SocietyID int64  `db:"society_id" json:"society_id"`
	Reference string `db:"reference" json:"reference"`
	BillID    int64  `db:"bill_id" json:"bill_id"`
	ClaimID   *int64 `db:"claim_id" json:"claim_id"`
	PaymentID *int64 `db:"payment_id" json:"payment_id"`
}

func (q *Queries) ReserveUPIReference(ctx context.Context, arg ReserveUPIReferenceParams) error {
	_, err := q.db.Exec(ctx, reserveUPIReference,
		arg.SocietyID,
		arg.Reference,
		arg.BillID,
		arg.ClaimID,
		arg.PaymentID,
	)
	return err
}

const reverseUPIPayment = `-- name: ReverseUPIPayment :one
UPDATE maintenance_payments SET status='reversed',reversed_by=$3,reversed_at=now(),reversal_reason=$4 WHERE society_id=$1 AND id=$2 AND status='verified' RETURNING id, society_id, bill_id, claim_id, payer_id, settings_version, amount_paise, reference, credit_date, receipt_number, verified_by, verified_at, status, reversed_by, reversed_at, reversal_reason, evidence_reference
`

type ReverseUPIPaymentParams struct {
	SocietyID      int64   `db:"society_id" json:"society_id"`
	ID             int64   `db:"id" json:"id"`
	ReversedBy     *int64  `db:"reversed_by" json:"reversed_by"`
	ReversalReason *string `db:"reversal_reason" json:"reversal_reason"`
}

func (q *Queries) ReverseUPIPayment(ctx context.Context, arg ReverseUPIPaymentParams) (MaintenancePayment, error) {
	row := q.db.QueryRow(ctx, reverseUPIPayment,
		arg.SocietyID,
		arg.ID,
		arg.ReversedBy,
		arg.ReversalReason,
	)
	var i MaintenancePayment
	err := row.Scan(
		&i.ID,
		&i.SocietyID,
		&i.BillID,
		&i.ClaimID,
		&i.PayerID,
		&i.SettingsVersion,
		&i.AmountPaise,
		&i.Reference,
		&i.CreditDate,
		&i.ReceiptNumber,
		&i.VerifiedBy,
		&i.VerifiedAt,
		&i.Status,
		&i.ReversedBy,
		&i.ReversedAt,
		&i.ReversalReason,
		&i.EvidenceReference,
	)
	return i, err
}

const reviewUPIClaim = `-- name: ReviewUPIClaim :one
UPDATE maintenance_payment_claims SET status=$3,reviewed_by=$4,reviewed_at=now(),reason=$5 WHERE society_id=$1 AND id=$2 AND status='pending' RETURNING id, society_id, bill_id, request_id, submitted_by, reference, payment_date, status, reviewed_by, reviewed_at, reason, created_at
`

type ReviewUPIClaimParams struct {
	SocietyID  int64   `db:"society_id" json:"society_id"`
	ID         int64   `db:"id" json:"id"`
	Status     string  `db:"status" json:"status"`
	ReviewedBy *int64  `db:"reviewed_by" json:"reviewed_by"`
	Reason     *string `db:"reason" json:"reason"`
}

func (q *Queries) ReviewUPIClaim(ctx context.Context, arg ReviewUPIClaimParams) (MaintenancePaymentClaim, error) {
	row := q.db.QueryRow(ctx, reviewUPIClaim,
		arg.SocietyID,
		arg.ID,
		arg.Status,
		arg.ReviewedBy,
		arg.Reason,
	)
	var i MaintenancePaymentClaim
	err := row.Scan(
		&i.ID,
		&i.SocietyID,
		&i.BillID,
		&i.RequestID,
		&i.SubmittedBy,
		&i.Reference,
		&i.PaymentDate,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const supersedeUPIRequests = `-- name: SupersedeUPIRequests :exec
UPDATE maintenance_payment_requests SET state='superseded' WHERE society_id=$1 AND state='active'
`

func (q *Queries) SupersedeUPIRequests(ctx context.Context, societyID int64) error {
	_, err := q.db.Exec(ctx, supersedeUPIRequests, societyID)
	return err
}

const uPICollectionSummary = `-- name: UPICollectionSummary :one
SELECT count(*)::bigint AS billed_count, COALESCE(sum(b.total_paise),0)::bigint AS billed_paise,
COALESCE(sum(v.paid_amount_paise),0)::bigint AS collected_paise,
COALESCE(sum(v.outstanding_amount_paise),0)::bigint AS outstanding_paise,
COALESCE(sum(v.outstanding_amount_paise) FILTER(WHERE v.payment_status='overdue'),0)::bigint AS overdue_paise,
count(*) FILTER(WHERE v.payment_claim_status='pending')::bigint AS pending_claims
FROM maintenance_bills b JOIN maintenance_bill_balances v ON v.bill_id=b.id
WHERE b.society_id=$1 AND ($2::bigint=0 OR b.flat_id=$2) AND ($3::date IS NULL OR b.billing_month=$3)
`

type UPICollectionSummaryParams struct {
	SocietyID int64       `db:"society_id" json:"society_id"`
	FlatID    int64       `db:"flat_id" json:"flat_id"`
	Month     pgtype.Date `db:"month" json:"month"`
}

type UPICollectionSummaryRow struct {
	BilledCount      int64 `db:"billed_count" json:"billed_count"`
	BilledPaise      int64 `db:"billed_paise" json:"billed_paise"`
	CollectedPaise   int64 `db:"collected_paise" json:"collected_paise"`
	OutstandingPaise int64 `db:"outstanding_paise" json:"outstanding_paise"`
	OverduePaise     int64 `db:"overdue_paise" json:"overdue_paise"`
	PendingClaims    int64 `db:"pending_claims" json:"pending_claims"`
}

func (q *Queries) UPICollectionSummary(ctx context.Context, arg UPICollectionSummaryParams) (UPICollectionSummaryRow, error) {
	row := q.db.QueryRow(ctx, uPICollectionSummary, arg.SocietyID, arg.FlatID, arg.Month)
	var i UPICollectionSummaryRow
	err := row.Scan(
		&i.BilledCount,
		&i.BilledPaise,
		&i.CollectedPaise,
		&i.OutstandingPaise,
		&i.OverduePaise,
		&i.PendingClaims,
	)
	return i, err
}

const updateUPIReport = `-- name: UpdateUPIReport :one
UPDATE maintenance_payment_reports SET status=$3,resolution_note=$4,updated_by=$5,updated_at=now() WHERE society_id=$1 AND id=$2 RETURNING id, society_id, bill_id, request_id, reported_by, reference, amount_paise, payment_date, explanation, fingerprint, status, resolution_note, updated_by, updated_at, created_at
`

type UpdateUPIReportParams struct {
	SocietyID      int64   `db:"society_id" json:"society_id"`
	ID             int64   `db:"id" json:"id"`
	Status         string  `db:"status" json:"status"`
	ResolutionNote *string `db:"resolution_note" json:"resolution_note"`
	UpdatedBy      *int64  `db:"updated_by" json:"updated_by"`
}

func (q *Queries) UpdateUPIReport(ctx context.Context, arg UpdateUPIReportParams) (MaintenancePaymentReport, error) {
	row := q.db.QueryRow(ctx, updateUPIReport,
		arg.SocietyID,
		arg.ID,
		arg.Status,
		arg.ResolutionNote,
		arg.UpdatedBy,
	)
	var i MaintenancePaymentReport
	err := row.Scan(
		&i.ID,
		&i.SocietyID,
		&i.BillID,
		&i.RequestID,
		&i.ReportedBy,
		&i.Reference,
		&i.AmountPaise,
		&i.PaymentDate,
		&i.Explanation,
		&i.Fingerprint,
		&i.Status,
		&i.ResolutionNote,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}
