// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: maintenance_outstanding_flats.sql

package db

import (
	"context"
)

const listMaintenanceOutstandingFlats = `-- name: ListMaintenanceOutstandingFlats :many
SELECT f.id, f.flat_number, f.block, f.flat_type, f.area_sqft_hundredths,
  COALESCE(sum(v.outstanding_amount_paise), 0)::bigint AS total_outstanding_paise,
  count(*)::bigint AS unpaid_bill_count,
  min(b.billing_month) AS oldest_unpaid_month
FROM flats f
JOIN maintenance_bills b ON b.flat_id = f.id AND b.society_id = f.society_id
JOIN maintenance_bill_balances v ON v.bill_id = b.id AND v.outstanding_amount_paise > 0
WHERE f.society_id = $1
  AND f.is_active
  AND ($2::bigint = 0 OR f.id < $2)
  AND ($3::text IS NULL OR COALESCE(f.block, '') ILIKE '%' || $3::text || '%')
  AND ($4::text IS NULL OR f.flat_number ILIKE '%' || $4::text || '%')
  AND (
    $5::text = ''
    OR f.flat_number ILIKE '%' || $5::text || '%'
    OR COALESCE(f.block, '') ILIKE '%' || $5::text || '%'
  )
GROUP BY f.id, f.flat_number, f.block, f.flat_type, f.area_sqft_hundredths
ORDER BY f.id DESC
LIMIT $6
`

type ListMaintenanceOutstandingFlatsParams struct {
	SocietyID  int64   `db:"society_id" json:"society_id"`
	BeforeID   int64   `db:"before_id" json:"before_id"`
	Block      *string `db:"block" json:"block"`
	FlatNumber *string `db:"flat_number" json:"flat_number"`
	Search     string  `db:"search" json:"search"`
	Limit      int32   `db:"limit" json:"limit"`
}

type ListMaintenanceOutstandingFlatsRow struct {
	ID                    int64       `db:"id" json:"id"`
	FlatNumber            string      `db:"flat_number" json:"flat_number"`
	Block                 *string     `db:"block" json:"block"`
	FlatType              *string     `db:"flat_type" json:"flat_type"`
	AreaSqftHundredths    *int64      `db:"area_sqft_hundredths" json:"area_sqft_hundredths"`
	TotalOutstandingPaise int64       `db:"total_outstanding_paise" json:"total_outstanding_paise"`
	UnpaidBillCount       int64       `db:"unpaid_bill_count" json:"unpaid_bill_count"`
	OldestUnpaidMonth     interface{} `db:"oldest_unpaid_month" json:"oldest_unpaid_month"`
}

func (q *Queries) ListMaintenanceOutstandingFlats(ctx context.Context, arg ListMaintenanceOutstandingFlatsParams) ([]ListMaintenanceOutstandingFlatsRow, error) {
	rows, err := q.db.Query(ctx, listMaintenanceOutstandingFlats,
		arg.SocietyID,
		arg.BeforeID,
		arg.Block,
		arg.FlatNumber,
		arg.Search,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMaintenanceOutstandingFlatsRow{}
	for rows.Next() {
		var i ListMaintenanceOutstandingFlatsRow
		if err := rows.Scan(
			&i.ID,
			&i.FlatNumber,
			&i.Block,
			&i.FlatType,
			&i.AreaSqftHundredths,
			&i.TotalOutstandingPaise,
			&i.UnpaidBillCount,
			&i.OldestUnpaidMonth,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
