// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notification_outbox.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimNotificationOutbox = `-- name: ClaimNotificationOutbox :one
UPDATE notification_outbox d SET attempts=d.attempts+1,available_at=now()+interval '2 minutes',lease_token=$1
WHERE d.id=(SELECT id FROM notification_outbox WHERE completed_at IS NULL AND available_at<=now() ORDER BY available_at,id FOR UPDATE SKIP LOCKED LIMIT 1) RETURNING d.id, d.user_id, d.society_id, d.flat_id, d.audience, d.event_key, d.payload, d.attempts, d.available_at, d.lease_token, d.inbox_completed_at, d.push_completed_at, d.completed_at, d.last_error, d.push_enabled, d.created_at
`

func (q *Queries) ClaimNotificationOutbox(ctx context.Context, leaseToken pgtype.UUID) (NotificationOutbox, error) {
	row := q.db.QueryRow(ctx, claimNotificationOutbox, leaseToken)
	var i NotificationOutbox
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SocietyID,
		&i.FlatID,
		&i.Audience,
		&i.EventKey,
		&i.Payload,
		&i.Attempts,
		&i.AvailableAt,
		&i.LeaseToken,
		&i.InboxCompletedAt,
		&i.PushCompletedAt,
		&i.CompletedAt,
		&i.LastError,
		&i.PushEnabled,
		&i.CreatedAt,
	)
	return i, err
}

const completeNotificationOutbox = `-- name: CompleteNotificationOutbox :exec
UPDATE notification_outbox SET completed_at=now(),push_completed_at=CASE WHEN $1::boolean THEN now() ELSE push_completed_at END,last_error=NULL
WHERE id=$2 AND lease_token=$3 AND available_at>now()
`

type CompleteNotificationOutboxParams struct {
	Delivered  bool        `db:"delivered" json:"delivered"`
	ID         int64       `db:"id" json:"id"`
	LeaseToken pgtype.UUID `db:"lease_token" json:"lease_token"`
}

func (q *Queries) CompleteNotificationOutbox(ctx context.Context, arg CompleteNotificationOutboxParams) error {
	_, err := q.db.Exec(ctx, completeNotificationOutbox, arg.Delivered, arg.ID, arg.LeaseToken)
	return err
}

const enqueueNotificationOutbox = `-- name: EnqueueNotificationOutbox :exec
INSERT INTO notification_outbox(user_id,society_id,flat_id,audience,event_key,payload) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(user_id,event_key) DO NOTHING
`

type EnqueueNotificationOutboxParams struct {
	UserID    int64  `db:"user_id" json:"user_id"`
	SocietyID int64  `db:"society_id" json:"society_id"`
	FlatID    *int64 `db:"flat_id" json:"flat_id"`
	Audience  string `db:"audience" json:"audience"`
	EventKey  string `db:"event_key" json:"event_key"`
	Payload   []byte `db:"payload" json:"payload"`
}

func (q *Queries) EnqueueNotificationOutbox(ctx context.Context, arg EnqueueNotificationOutboxParams) error {
	_, err := q.db.Exec(ctx, enqueueNotificationOutbox,
		arg.UserID,
		arg.SocietyID,
		arg.FlatID,
		arg.Audience,
		arg.EventKey,
		arg.Payload,
	)
	return err
}

const markOutboxInbox = `-- name: MarkOutboxInbox :execrows
UPDATE notification_outbox SET inbox_completed_at=now() WHERE id=$1 AND lease_token=$2 AND available_at>now() AND completed_at IS NULL
`

type MarkOutboxInboxParams struct {
	ID         int64       `db:"id" json:"id"`
	LeaseToken pgtype.UUID `db:"lease_token" json:"lease_token"`
}

func (q *Queries) MarkOutboxInbox(ctx context.Context, arg MarkOutboxInboxParams) (int64, error) {
	result, err := q.db.Exec(ctx, markOutboxInbox, arg.ID, arg.LeaseToken)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const notificationBacklog = `-- name: NotificationBacklog :one
SELECT count(*)::bigint AS pending,COALESCE(extract(epoch FROM now()-min(available_at)),0)::double precision AS oldest_seconds FROM notification_outbox WHERE completed_at IS NULL
`

type NotificationBacklogRow struct {
	Pending       int64   `db:"pending" json:"pending"`
	OldestSeconds float64 `db:"oldest_seconds" json:"oldest_seconds"`
}

func (q *Queries) NotificationBacklog(ctx context.Context) (NotificationBacklogRow, error) {
	row := q.db.QueryRow(ctx, notificationBacklog)
	var i NotificationBacklogRow
	err := row.Scan(&i.Pending, &i.OldestSeconds)
	return i, err
}

const notificationOutboxAccess = `-- name: NotificationOutboxAccess :one
SELECT EXISTS(SELECT 1 FROM society_members m JOIN societies s ON s.id=m.society_id
WHERE m.society_id=$1 AND m.user_id=$2 AND m.status='active' AND s.status='active' AND s.deleted_at IS NULL
AND (($3::text='admin' AND m.role IN ('owner','admin'))
OR ($3::text='hub_member' AND m.role IN ('owner','admin','resident') AND EXISTS(SELECT 1 FROM users hu WHERE hu.id=m.user_id AND hu.is_active AND NOT hu.is_blocked AND hu.deleted_at IS NULL))
OR ($3::text='staff' AND m.role='staff')
OR ($3::text IN ('resident','society_resident') AND m.role<>'staff' AND EXISTS(
 SELECT 1 FROM flat_residents r JOIN flats f ON f.id=r.flat_id AND f.society_id=r.society_id AND f.is_active
 WHERE r.society_id=m.society_id AND r.user_id=m.user_id AND r.status='active' AND ($3::text='society_resident' OR r.flat_id=$4)
))))::boolean
`

type NotificationOutboxAccessParams struct {
	SocietyID int64  `db:"society_id" json:"society_id"`
	UserID    int64  `db:"user_id" json:"user_id"`
	Audience  string `db:"audience" json:"audience"`
	FlatID    *int64 `db:"flat_id" json:"flat_id"`
}

func (q *Queries) NotificationOutboxAccess(ctx context.Context, arg NotificationOutboxAccessParams) (bool, error) {
	row := q.db.QueryRow(ctx, notificationOutboxAccess,
		arg.SocietyID,
		arg.UserID,
		arg.Audience,
		arg.FlatID,
	)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const outboxInboxID = `-- name: OutboxInboxID :one
SELECT id FROM notifications WHERE user_id=$1 AND event_key=$2
`

type OutboxInboxIDParams struct {
	UserID   int64   `db:"user_id" json:"user_id"`
	EventKey *string `db:"event_key" json:"event_key"`
}

func (q *Queries) OutboxInboxID(ctx context.Context, arg OutboxInboxIDParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, outboxInboxID, arg.UserID, arg.EventKey)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const retryNotificationOutbox = `-- name: RetryNotificationOutbox :exec
UPDATE notification_outbox SET available_at=now()+(LEAST(3600,30*power(2,LEAST(attempts,7)))::int*interval '1 second'),lease_token=NULL,last_error='delivery_failed'
WHERE id=$1 AND lease_token=$2
`

type RetryNotificationOutboxParams struct {
	ID         int64       `db:"id" json:"id"`
	LeaseToken pgtype.UUID `db:"lease_token" json:"lease_token"`
}

func (q *Queries) RetryNotificationOutbox(ctx context.Context, arg RetryNotificationOutboxParams) error {
	_, err := q.db.Exec(ctx, retryNotificationOutbox, arg.ID, arg.LeaseToken)
	return err
}
