// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUnreadNotificationsByUser = `-- name: CountUnreadNotificationsByUser :one
SELECT COUNT(*)
FROM notifications
WHERE user_id = $1
  AND read_at IS NULL
`

func (q *Queries) CountUnreadNotificationsByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadNotificationsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (
    id,
    user_id,
    society_id,
    flat_id,
    type,
    title,
    body,
    data,
    event_key
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (user_id, event_key) DO NOTHING
RETURNING id, user_id, society_id, flat_id, type, title, body, data, event_key, read_at, created_at, domain
`

type CreateNotificationParams struct {
	ID        pgtype.UUID `db:"id" json:"id"`
	UserID    int64       `db:"user_id" json:"user_id"`
	SocietyID *int64      `db:"society_id" json:"society_id"`
	FlatID    *int64      `db:"flat_id" json:"flat_id"`
	Type      string      `db:"type" json:"type"`
	Title     string      `db:"title" json:"title"`
	Body      string      `db:"body" json:"body"`
	Data      []byte      `db:"data" json:"data"`
	EventKey  *string     `db:"event_key" json:"event_key"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.ID,
		arg.UserID,
		arg.SocietyID,
		arg.FlatID,
		arg.Type,
		arg.Title,
		arg.Body,
		arg.Data,
		arg.EventKey,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SocietyID,
		&i.FlatID,
		&i.Type,
		&i.Title,
		&i.Body,
		&i.Data,
		&i.EventKey,
		&i.ReadAt,
		&i.CreatedAt,
		&i.Domain,
	)
	return i, err
}

const getOwnedNotification = `-- name: GetOwnedNotification :one
SELECT id, user_id, society_id, flat_id, type, title, body, data, event_key, read_at, created_at, domain FROM notifications WHERE user_id = $1 AND id = $2
`

type GetOwnedNotificationParams struct {
	UserID int64       `db:"user_id" json:"user_id"`
	ID     pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) GetOwnedNotification(ctx context.Context, arg GetOwnedNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, getOwnedNotification, arg.UserID, arg.ID)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SocietyID,
		&i.FlatID,
		&i.Type,
		&i.Title,
		&i.Body,
		&i.Data,
		&i.EventKey,
		&i.ReadAt,
		&i.CreatedAt,
		&i.Domain,
	)
	return i, err
}

const listNotificationsByUser = `-- name: ListNotificationsByUser :many
SELECT id, user_id, society_id, flat_id, type, title, body, data, event_key, read_at, created_at, domain
FROM notifications
WHERE user_id = $1
  AND (
    $2::timestamptz IS NULL
    OR created_at < $2::timestamptz
    OR (created_at = $2::timestamptz AND id < $3::uuid)
  )
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListNotificationsByUserParams struct {
	UserID          int64              `db:"user_id" json:"user_id"`
	CursorCreatedAt pgtype.Timestamptz `db:"cursor_created_at" json:"cursor_created_at"`
	CursorID        pgtype.UUID        `db:"cursor_id" json:"cursor_id"`
	Limit           int32              `db:"limit" json:"limit"`
}

func (q *Queries) ListNotificationsByUser(ctx context.Context, arg ListNotificationsByUserParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotificationsByUser,
		arg.UserID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SocietyID,
			&i.FlatID,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.Data,
			&i.EventKey,
			&i.ReadAt,
			&i.CreatedAt,
			&i.Domain,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :exec
UPDATE notifications
SET read_at = COALESCE(read_at, NOW())
WHERE user_id = $1
  AND read_at IS NULL
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, markAllNotificationsRead, userID)
	return err
}

const markNotificationRead = `-- name: MarkNotificationRead :one
UPDATE notifications
SET read_at = COALESCE(read_at, NOW())
WHERE id = $1
  AND user_id = $2
RETURNING id, user_id, society_id, flat_id, type, title, body, data, event_key, read_at, created_at, domain
`

type MarkNotificationReadParams struct {
	ID     pgtype.UUID `db:"id" json:"id"`
	UserID int64       `db:"user_id" json:"user_id"`
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (Notification, error) {
	row := q.db.QueryRow(ctx, markNotificationRead, arg.ID, arg.UserID)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SocietyID,
		&i.FlatID,
		&i.Type,
		&i.Title,
		&i.Body,
		&i.Data,
		&i.EventKey,
		&i.ReadAt,
		&i.CreatedAt,
		&i.Domain,
	)
	return i, err
}
