// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: short_links.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createShortLink = `-- name: CreateShortLink :one
INSERT INTO short_links (
    short_code,
    resource_type,
    resource_id,
    expires_at,
    created_by,
    metadata
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    COALESCE($6, '{}'::jsonb)
)
RETURNING id, short_code, resource_type, resource_id, expires_at, revoked_at, created_by, metadata, created_at, updated_at
`

type CreateShortLinkParams struct {
	ShortCode    string             `db:"short_code" json:"short_code"`
	ResourceType string             `db:"resource_type" json:"resource_type"`
	ResourceID   int64              `db:"resource_id" json:"resource_id"`
	ExpiresAt    pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	CreatedBy    *int64             `db:"created_by" json:"created_by"`
	Metadata     interface{}        `db:"metadata" json:"metadata"`
}

func (q *Queries) CreateShortLink(ctx context.Context, arg CreateShortLinkParams) (ShortLink, error) {
	row := q.db.QueryRow(ctx, createShortLink,
		arg.ShortCode,
		arg.ResourceType,
		arg.ResourceID,
		arg.ExpiresAt,
		arg.CreatedBy,
		arg.Metadata,
	)
	var i ShortLink
	err := row.Scan(
		&i.ID,
		&i.ShortCode,
		&i.ResourceType,
		&i.ResourceID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedBy,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getShortLinkByCode = `-- name: GetShortLinkByCode :one
SELECT id, short_code, resource_type, resource_id, expires_at, revoked_at, created_by, metadata, created_at, updated_at
FROM short_links
WHERE short_code = $1
`

func (q *Queries) GetShortLinkByCode(ctx context.Context, shortCode string) (ShortLink, error) {
	row := q.db.QueryRow(ctx, getShortLinkByCode, shortCode)
	var i ShortLink
	err := row.Scan(
		&i.ID,
		&i.ShortCode,
		&i.ResourceType,
		&i.ResourceID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedBy,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getShortLinkByResource = `-- name: GetShortLinkByResource :one
SELECT id, short_code, resource_type, resource_id, expires_at, revoked_at, created_by, metadata, created_at, updated_at
FROM short_links
WHERE resource_type = $1
  AND resource_id = $2
  AND revoked_at IS NULL
ORDER BY created_at DESC
LIMIT 1
`

type GetShortLinkByResourceParams struct {
	ResourceType string `db:"resource_type" json:"resource_type"`
	ResourceID   int64  `db:"resource_id" json:"resource_id"`
}

func (q *Queries) GetShortLinkByResource(ctx context.Context, arg GetShortLinkByResourceParams) (ShortLink, error) {
	row := q.db.QueryRow(ctx, getShortLinkByResource, arg.ResourceType, arg.ResourceID)
	var i ShortLink
	err := row.Scan(
		&i.ID,
		&i.ShortCode,
		&i.ResourceType,
		&i.ResourceID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedBy,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const revokeShortLink = `-- name: RevokeShortLink :one
UPDATE short_links
SET revoked_at = NOW(),
    updated_at = NOW()
WHERE short_code = $1
  AND revoked_at IS NULL
RETURNING id, short_code, resource_type, resource_id, expires_at, revoked_at, created_by, metadata, created_at, updated_at
`

func (q *Queries) RevokeShortLink(ctx context.Context, shortCode string) (ShortLink, error) {
	row := q.db.QueryRow(ctx, revokeShortLink, shortCode)
	var i ShortLink
	err := row.Scan(
		&i.ID,
		&i.ShortCode,
		&i.ResourceType,
		&i.ResourceID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedBy,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
