// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: web_push.sql

package db

import (
	"context"
)

const deletePreviousWebInstallation = `-- name: DeletePreviousWebInstallation :exec
DELETE FROM device_tokens WHERE platform = 'web'
AND (token = $1 OR device_id = $2)
`

type DeletePreviousWebInstallationParams struct {
	Token    string  `db:"token" json:"token"`
	DeviceID *string `db:"device_id" json:"device_id"`
}

func (q *Queries) DeletePreviousWebInstallation(ctx context.Context, arg DeletePreviousWebInstallationParams) error {
	_, err := q.db.Exec(ctx, deletePreviousWebInstallation, arg.Token, arg.DeviceID)
	return err
}

const insertWebDeviceToken = `-- name: InsertWebDeviceToken :one
INSERT INTO device_tokens(user_id, token, platform, device_id, session_version)
VALUES ($1, $2, 'web', $3, $4) RETURNING id, user_id, token, platform, device_id, last_seen_at, created_at, updated_at, session_version
`

type InsertWebDeviceTokenParams struct {
	UserID         int64   `db:"user_id" json:"user_id"`
	Token          string  `db:"token" json:"token"`
	DeviceID       *string `db:"device_id" json:"device_id"`
	SessionVersion *int64  `db:"session_version" json:"session_version"`
}

func (q *Queries) InsertWebDeviceToken(ctx context.Context, arg InsertWebDeviceTokenParams) (DeviceToken, error) {
	row := q.db.QueryRow(ctx, insertWebDeviceToken,
		arg.UserID,
		arg.Token,
		arg.DeviceID,
		arg.SessionVersion,
	)
	var i DeviceToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.Platform,
		&i.DeviceID,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SessionVersion,
	)
	return i, err
}

const listEligibleWebTokens = `-- name: ListEligibleWebTokens :many
SELECT d.id, d.user_id, d.token, d.platform, d.device_id, d.last_seen_at, d.created_at, d.updated_at, d.session_version FROM device_tokens d JOIN users u ON u.id = d.user_id
WHERE d.user_id = $1 AND d.platform = 'web'
AND d.session_version = u.session_version
AND u.is_active AND NOT u.is_blocked AND u.deleted_at IS NULL
AND (EXISTS (SELECT 1 FROM flat_residents r JOIN flats f ON f.id = r.flat_id JOIN societies s ON s.id = r.society_id
  WHERE r.user_id = u.id AND r.status = 'active' AND f.is_active AND s.status = 'active' AND s.deleted_at IS NULL
  AND ($2::bigint = 0 OR r.society_id = $2)
  AND ($3::bigint = 0 OR r.flat_id = $3))
 OR ($3::bigint = 0 AND EXISTS (SELECT 1 FROM society_members m JOIN societies s ON s.id = m.society_id
  WHERE m.user_id = u.id AND m.role = 'resident' AND m.status = 'active' AND s.status = 'active' AND s.deleted_at IS NULL
  AND ($2::bigint = 0 OR m.society_id = $2)))
) ORDER BY d.id
`

type ListEligibleWebTokensParams struct {
	UserID    int64 `db:"user_id" json:"user_id"`
	SocietyID int64 `db:"society_id" json:"society_id"`
	FlatID    int64 `db:"flat_id" json:"flat_id"`
}

func (q *Queries) ListEligibleWebTokens(ctx context.Context, arg ListEligibleWebTokensParams) ([]DeviceToken, error) {
	rows, err := q.db.Query(ctx, listEligibleWebTokens, arg.UserID, arg.SocietyID, arg.FlatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeviceToken{}
	for rows.Next() {
		var i DeviceToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Token,
			&i.Platform,
			&i.DeviceID,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SessionVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockWebPushUser = `-- name: LockWebPushUser :one
SELECT u.id FROM users u
WHERE u.id = $1 AND u.session_version = $2
AND u.is_active AND NOT u.is_blocked AND u.deleted_at IS NULL
AND (EXISTS (SELECT 1 FROM flat_residents r JOIN flats f ON f.id = r.flat_id JOIN societies s ON s.id = r.society_id WHERE r.user_id = u.id AND r.status = 'active' AND f.is_active AND s.status = 'active' AND s.deleted_at IS NULL)
 OR EXISTS (SELECT 1 FROM society_members m JOIN societies s ON s.id = m.society_id WHERE m.user_id = u.id AND m.role = 'resident' AND m.status = 'active' AND s.status = 'active' AND s.deleted_at IS NULL))
FOR SHARE OF u
`

type LockWebPushUserParams struct {
	UserID         int64 `db:"user_id" json:"user_id"`
	SessionVersion int64 `db:"session_version" json:"session_version"`
}

func (q *Queries) LockWebPushUser(ctx context.Context, arg LockWebPushUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, lockWebPushUser, arg.UserID, arg.SessionVersion)
	var id int64
	err := row.Scan(&id)
	return id, err
}
